<script lang="ts">
	import { onMount } from 'svelte';
	import { api } from '$lib/api';
	import { viewerTimeZone } from '$lib/time';
	import { formatNaira, parseNairaToMinor } from '$lib/money';
	let { params } = $props();
	type Offer = { id:string; seller:string; buyer_name:string; duration_minutes:number; state:string; version:number; amount_minor:string; expires_at:string; role:'seller'|'buyer'; local_simulator:boolean; provider_checkout_enabled:boolean; timezone:string };
	type Slot = { starts_at:string; local_label:string };
	let offer=$state<Offer|null>(null), loading=$state(true), busy=$state(false), message=$state(''), counter=$state(''), date=$state(''), selected=$state(''), slots=$state<Slot[]>([]), key=$state('');
	async function load(){try{offer=await api<Offer>(`/api/v1/offers/${encodeURIComponent(params.id)}`);counter=String(Number(offer.amount_minor)/100);if(offer.state==='agreed'&&offer.role==='buyer'){if(!date){const now=new Date();date=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-${String(now.getDate()).padStart(2,'0')}`}await loadSlots()}}catch(e){message=e instanceof Error?e.message:'This offer is unavailable. Verify the email used to make it.'}finally{loading=false}}
	async function loadSlots(){if(!offer||!date)return;selected='';try{slots=(await api<{slots:Slot[]}>(`/api/v1/people/${encodeURIComponent(offer.seller)}/slots?date=${encodeURIComponent(date)}&duration=${offer.duration_minutes}&tz=${encodeURIComponent(viewerTimeZone())}`)).slots}catch(e){slots=[];message=e instanceof Error?e.message:'Available times could not be loaded.'}}
	async function respond(action:'accept'|'counter'|'decline'|'withdraw'){if(!offer)return;message='';const parsed=parseNairaToMinor(counter);if(action==='counter'&&(parsed===null||parsed<100n||parsed>100000000n)){message='Enter a counteroffer between ₦1 and ₦1,000,000.';return}busy=true;try{await api(`/api/v1/offers/${encodeURIComponent(offer.id)}/${action}`,{method:'POST',body:JSON.stringify({version:offer.version,amount_minor:parsed===null?0:Number(parsed)})});await load();message='Offer updated. Agreement does not create a booking or collect payment.'}catch(e){message=e instanceof Error?e.message:'The offer could not be updated.'}finally{busy=false}}
	async function checkout(){if(!offer||!selected)return;busy=true;message='';try{if(!key)key=crypto.randomUUID()+crypto.randomUUID();const quote=await api<{id:string}>(`/api/v1/offers/${encodeURIComponent(offer.id)}/checkout`,{method:'POST',headers:{'Idempotency-Key':key},body:JSON.stringify({starts_at:selected})});location.href=`/checkout/${encodeURIComponent(quote.id)}`}catch(e){message=e instanceof Error?e.message:'Checkout could not be started.'}finally{busy=false}}
	onMount(load);
</script>
<svelte:head><title>Offer — WantMyTime</title><meta name="robots" content="noindex,nofollow" /></svelte:head>
<section class="form-page"><a class="back-link" href="/">← WantMyTime</a><p class="eyebrow">Private offer</p><h1 class="page-heading">Your offer.</h1>
	{#if loading}<p class="page-intro">Loading your offer…</p>{:else if !offer}<div class="notice notice-warning">{message}<p><a href={`/access?next=${encodeURIComponent(`/offer/${params.id}`)}`}>Open it with your email ↗</a></p></div>{:else}
		<div class="appointment-slip"><div><small>{offer.role==='seller'?'FROM':'TO'}</small><strong>{offer.role==='seller'?offer.buyer_name:offer.seller}</strong></div><div><small>LENGTH</small><strong>{offer.duration_minutes} minutes</strong></div><div><small>AMOUNT</small><strong>{formatNaira(offer.amount_minor)}</strong></div><div><small>STATUS</small><strong>{offer.state.replaceAll('_',' ')}</strong></div></div>
		{#if offer.state==='pending'&&offer.role==='seller'}<div class="setup-form"><button class="button" onclick={()=>respond('accept')} disabled={busy}>Accept offer</button><label>Counter once<div class="money-input"><span>₦</span><input bind:value={counter} inputmode="decimal" /></div></label><button class="button button-secondary" onclick={()=>respond('counter')} disabled={busy}>Send counteroffer</button><button class="text-link" onclick={()=>respond('decline')} disabled={busy}>Decline</button></div>
		{:else if offer.role==='buyer'&&(offer.state==='pending'||offer.state==='countered')}<p class="page-intro">Waiting for the seller. No payment has been taken.</p>{#if offer.state==='countered'}<button class="button" onclick={()=>respond('accept')} disabled={busy}>Accept counteroffer</button><button class="button button-secondary" onclick={()=>respond('decline')} disabled={busy}>Decline counteroffer</button>{/if}<button class="text-link" onclick={()=>respond('withdraw')} disabled={busy}>Withdraw offer</button>
		{:else if offer.state==='agreed'&&offer.role==='buyer'}<p class="page-intro">The agreed amount is held for checkout. Choose a time to continue; payment is confirmed only after provider verification.</p><div class="setup-form"><label>Date<input class="field" type="date" bind:value={date} onchange={loadSlots} /></label>{#if slots.length}<fieldset><legend>Available times · {offer.timezone}</legend><div class="slot-list">{#each slots as slot}<button class="slot-option" class:selected={selected===slot.starts_at} onclick={()=>selected=slot.starts_at}>{slot.local_label}</button>{/each}</div></fieldset>{:else}<p class="form-note">No times available on this date.</p>{/if}<button class="button" onclick={checkout} disabled={!selected||busy||(!offer.local_simulator&&!offer.provider_checkout_enabled)}>Continue to checkout</button>{#if offer.local_simulator}<p class="form-note">Local simulator only. No money is collected.</p>{/if}</div>{/if}
		{#if message}<p class="notice notice-info" aria-live="polite">{message}</p>{/if}
	{/if}
</section>
