<script lang="ts">
	import { onMount } from 'svelte';
	import { api } from '$lib/api';
	let quoteId=$state('');let reference=$state('');let paymentState=$state<'checking'|'paid'|'pending'|'review'|'error'>('checking');let message=$state('Checking the payment directly with the provider…');let busy=$state(false);
	onMount(()=>{const query=new URLSearchParams(window.location.search);quoteId=query.get('quote_id')??'';reference=query.get('reference')??query.get('trxref')??'';void verify()});
	async function verify(){if(!quoteId||!reference){paymentState='error';message='The payment return is missing its checkout reference. Sign in and contact support with the provider reference.';return}busy=true;paymentState='checking';message='Checking the payment directly with the provider…';try{const result=await api<{state:string;booking_id:string|null}>(`/api/v1/quotes/${encodeURIComponent(quoteId)}/verify-payment`,{method:'POST',body:JSON.stringify({reference})});if(result.booking_id){paymentState='paid';message='Payment verified. Your booking is confirmed.';window.location.replace(`/booking/${encodeURIComponent(result.booking_id)}`)}else if(result.state==='review'){paymentState='review';message='The provider reports a successful charge, but the booking needs manual review. Do not pay again. Save this reference and contact support.'}else{paymentState='pending';message='The provider has not confirmed a successful payment yet. You can check again safely.'}}catch(error){paymentState='error';message=error instanceof Error?error.message:'Payment status could not be checked. You can safely retry.'}finally{busy=false}}
</script>
<svelte:head><title>Checking payment — WantMyTime</title><meta name="robots" content="noindex,nofollow" /></svelte:head>
<section class="form-page"><p class="eyebrow">Payment status</p><h1 class="page-heading">{paymentState==='paid'?'Your time is confirmed.':paymentState==='checking'?'Checking your payment.':paymentState==='review'?'Your payment needs a review.':'We’re checking your payment.'}</h1><p class="page-intro" aria-live="polite">{message}</p>{#if paymentState==='pending'||paymentState==='error'}<button class="button" onclick={verify} disabled={busy||!quoteId||!reference}>{busy?'Checking…':'Check payment status again'}</button>{/if}{#if paymentState==='error'}<p class="form-note">A redirect alone never confirms payment. No booking will be marked paid without provider verification.</p><a class="button button-secondary" href={`/access?next=${encodeURIComponent(`/payment/return?quote_id=${quoteId}&reference=${reference}`)}`}>Verify your email to continue</a>{/if}</section>
