// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: calendar.sql

package store

import (
	"context"
	"time"
)

const busyBlocksBetween = `-- name: BusyBlocksBetween :many
SELECT lower(busy)::timestamptz AS starts_at, upper(busy)::timestamptz AS ends_at
FROM calendar_busy_blocks
WHERE seller_id = $1::uuid AND busy && tstzrange($2::timestamptz, $3::timestamptz, '[)')
`

type BusyBlocksBetweenParams struct {
	SellerID string
	FromAt   time.Time
	ToAt     time.Time
}

type BusyBlocksBetweenRow struct {
	StartsAt time.Time
	EndsAt   time.Time
}

func (q *Queries) BusyBlocksBetween(ctx context.Context, arg BusyBlocksBetweenParams) ([]BusyBlocksBetweenRow, error) {
	rows, err := q.db.Query(ctx, busyBlocksBetween, arg.SellerID, arg.FromAt, arg.ToAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BusyBlocksBetweenRow
	for rows.Next() {
		var i BusyBlocksBetweenRow
		if err := rows.Scan(&i.StartsAt, &i.EndsAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const calendarBookingContext = `-- name: CalendarBookingContext :one
SELECT b.id::text AS booking_id, b.seller_id::text AS seller_id, b.state, b.starts_at, b.duration_minutes, b.buyer_name, sp.handle,
       COALESCE(b.calendar_event_id, '')::text AS calendar_event_id, (b.meeting_url IS NOT NULL)::boolean AS has_meeting_link,
       COALESCE(b.meeting_source, '')::text AS meeting_source
FROM bookings b JOIN seller_profiles sp ON sp.id = b.seller_id
WHERE b.id = $1::uuid
`

type CalendarBookingContextRow struct {
	BookingID       string
	SellerID        string
	State           string
	StartsAt        time.Time
	DurationMinutes int32
	BuyerName       string
	Handle          string
	CalendarEventID string
	HasMeetingLink  bool
	MeetingSource   string
}

func (q *Queries) CalendarBookingContext(ctx context.Context, bookingID string) (CalendarBookingContextRow, error) {
	row := q.db.QueryRow(ctx, calendarBookingContext, bookingID)
	var i CalendarBookingContextRow
	err := row.Scan(
		&i.BookingID,
		&i.SellerID,
		&i.State,
		&i.StartsAt,
		&i.DurationMinutes,
		&i.BuyerName,
		&i.Handle,
		&i.CalendarEventID,
		&i.HasMeetingLink,
		&i.MeetingSource,
	)
	return i, err
}

const calendarBusyConflict = `-- name: CalendarBusyConflict :one
SELECT EXISTS (
  SELECT 1 FROM calendar_busy_blocks bb
  WHERE bb.seller_id = $1::uuid
    AND bb.busy && tstzrange($2::timestamptz, $3::timestamptz, '[)')
    AND NOT EXISTS (
      SELECT 1 FROM bookings own
      WHERE own.id = $4::uuid
        AND tstzrange(own.starts_at, own.starts_at + own.duration_minutes * interval '1 minute', '[]') @> bb.busy
    )
)::boolean
`

type CalendarBusyConflictParams struct {
	SellerID        string
	FromAt          time.Time
	ToAt            time.Time
	IgnoreBookingID *string
}

// Busy ranges that sit entirely inside the booking being moved are that
// booking's own calendar event, so they do not block its new time.
func (q *Queries) CalendarBusyConflict(ctx context.Context, arg CalendarBusyConflictParams) (bool, error) {
	row := q.db.QueryRow(ctx, calendarBusyConflict,
		arg.SellerID,
		arg.FromAt,
		arg.ToAt,
		arg.IgnoreBookingID,
	)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const calendarConnection = `-- name: CalendarConnection :one
SELECT seller_id::text AS seller_id, account_email, encrypted_refresh_token, check_busy, add_events, create_meet_links, status
FROM calendar_connections WHERE seller_id = $1::uuid
`

type CalendarConnectionRow struct {
	SellerID              string
	AccountEmail          string
	EncryptedRefreshToken []byte
	CheckBusy             bool
	AddEvents             bool
	CreateMeetLinks       bool
	Status                string
}

func (q *Queries) CalendarConnection(ctx context.Context, sellerID string) (CalendarConnectionRow, error) {
	row := q.db.QueryRow(ctx, calendarConnection, sellerID)
	var i CalendarConnectionRow
	err := row.Scan(
		&i.SellerID,
		&i.AccountEmail,
		&i.EncryptedRefreshToken,
		&i.CheckBusy,
		&i.AddEvents,
		&i.CreateMeetLinks,
		&i.Status,
	)
	return i, err
}

const calendarConnectionForUser = `-- name: CalendarConnectionForUser :one
SELECT c.seller_id::text AS seller_id, c.account_email, c.check_busy, c.add_events, c.create_meet_links, c.status, c.last_error, c.last_synced_at, c.connected_at,
       c.encrypted_refresh_token
FROM calendar_connections c JOIN seller_profiles sp ON sp.id = c.seller_id
WHERE sp.user_id = $1
`

type CalendarConnectionForUserRow struct {
	SellerID              string
	AccountEmail          string
	CheckBusy             bool
	AddEvents             bool
	CreateMeetLinks       bool
	Status                string
	LastError             *string
	LastSyncedAt          *time.Time
	ConnectedAt           time.Time
	EncryptedRefreshToken []byte
}

func (q *Queries) CalendarConnectionForUser(ctx context.Context, userID string) (CalendarConnectionForUserRow, error) {
	row := q.db.QueryRow(ctx, calendarConnectionForUser, userID)
	var i CalendarConnectionForUserRow
	err := row.Scan(
		&i.SellerID,
		&i.AccountEmail,
		&i.CheckBusy,
		&i.AddEvents,
		&i.CreateMeetLinks,
		&i.Status,
		&i.LastError,
		&i.LastSyncedAt,
		&i.ConnectedAt,
		&i.EncryptedRefreshToken,
	)
	return i, err
}

const claimCalendarJobs = `-- name: ClaimCalendarJobs :many
WITH claimable AS (
  SELECT id FROM calendar_jobs
  WHERE attempts < 10 AND ((state = 'queued' AND due_at <= now()) OR (state = 'processing' AND claimed_at < now() - interval '5 minutes'))
  ORDER BY due_at, id
  FOR UPDATE SKIP LOCKED
  LIMIT $1::int
)
UPDATE calendar_jobs j SET state = 'processing', claimed_at = now(), attempts = j.attempts + 1, updated_at = now()
FROM claimable c WHERE j.id = c.id
RETURNING j.id::text AS id, j.booking_id::text AS booking_id, j.attempts
`

type ClaimCalendarJobsRow struct {
	ID        string
	BookingID string
	Attempts  int16
}

func (q *Queries) ClaimCalendarJobs(ctx context.Context, batchSize int32) ([]ClaimCalendarJobsRow, error) {
	rows, err := q.db.Query(ctx, claimCalendarJobs, batchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimCalendarJobsRow
	for rows.Next() {
		var i ClaimCalendarJobsRow
		if err := rows.Scan(&i.ID, &i.BookingID, &i.Attempts); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const connectionsDueForBusySync = `-- name: ConnectionsDueForBusySync :many
SELECT c.seller_id::text AS seller_id, sp.booking_horizon_days
FROM calendar_connections c JOIN seller_profiles sp ON sp.id = c.seller_id
WHERE c.status IN ('active', 'error') AND c.check_busy
  AND (c.last_synced_at IS NULL OR c.last_synced_at < now() - make_interval(secs => $1::int))
ORDER BY c.last_synced_at NULLS FIRST
LIMIT $2::int
`

type ConnectionsDueForBusySyncParams struct {
	MaxAgeSeconds int32
	BatchSize     int32
}

type ConnectionsDueForBusySyncRow struct {
	SellerID           string
	BookingHorizonDays int16
}

func (q *Queries) ConnectionsDueForBusySync(ctx context.Context, arg ConnectionsDueForBusySyncParams) ([]ConnectionsDueForBusySyncRow, error) {
	rows, err := q.db.Query(ctx, connectionsDueForBusySync, arg.MaxAgeSeconds, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ConnectionsDueForBusySyncRow
	for rows.Next() {
		var i ConnectionsDueForBusySyncRow
		if err := rows.Scan(&i.SellerID, &i.BookingHorizonDays); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const consumeOAuthState = `-- name: ConsumeOAuthState :one
DELETE FROM oauth_states WHERE state_hash = $1 AND expires_at > now()
RETURNING user_id::text AS user_id, code_verifier
`

type ConsumeOAuthStateRow struct {
	UserID       string
	CodeVerifier string
}

func (q *Queries) ConsumeOAuthState(ctx context.Context, stateHash []byte) (ConsumeOAuthStateRow, error) {
	row := q.db.QueryRow(ctx, consumeOAuthState, stateHash)
	var i ConsumeOAuthStateRow
	err := row.Scan(&i.UserID, &i.CodeVerifier)
	return i, err
}

const createOAuthState = `-- name: CreateOAuthState :exec
INSERT INTO oauth_states(state_hash, user_id, code_verifier, expires_at)
VALUES ($1, $2::uuid, $3, now() + interval '10 minutes')
`

type CreateOAuthStateParams struct {
	StateHash    []byte
	UserID       string
	CodeVerifier string
}

func (q *Queries) CreateOAuthState(ctx context.Context, arg CreateOAuthStateParams) error {
	_, err := q.db.Exec(ctx, createOAuthState, arg.StateHash, arg.UserID, arg.CodeVerifier)
	return err
}

const deleteBusyBlocks = `-- name: DeleteBusyBlocks :exec
DELETE FROM calendar_busy_blocks WHERE seller_id = $1::uuid
`

func (q *Queries) DeleteBusyBlocks(ctx context.Context, sellerID string) error {
	_, err := q.db.Exec(ctx, deleteBusyBlocks, sellerID)
	return err
}

const deleteCalendarConnection = `-- name: DeleteCalendarConnection :exec
DELETE FROM calendar_connections WHERE seller_id = $1::uuid
`

func (q *Queries) DeleteCalendarConnection(ctx context.Context, sellerID string) error {
	_, err := q.db.Exec(ctx, deleteCalendarConnection, sellerID)
	return err
}

const enqueueCalendarSync = `-- name: EnqueueCalendarSync :exec
INSERT INTO calendar_jobs(booking_id)
SELECT b.id FROM bookings b
JOIN calendar_connections c ON c.seller_id = b.seller_id AND c.status IN ('active', 'error') AND (c.add_events OR c.create_meet_links)
WHERE b.id = $1::uuid
ON CONFLICT (booking_id) WHERE state = 'queued' DO UPDATE SET due_at = LEAST(calendar_jobs.due_at, now())
`

func (q *Queries) EnqueueCalendarSync(ctx context.Context, bookingID string) error {
	_, err := q.db.Exec(ctx, enqueueCalendarSync, bookingID)
	return err
}

const enqueueCalendarSyncForSeller = `-- name: EnqueueCalendarSyncForSeller :exec
INSERT INTO calendar_jobs(booking_id)
SELECT b.id FROM bookings b
WHERE b.seller_id = $1::uuid AND b.state = 'confirmed' AND b.starts_at > now()
ON CONFLICT (booking_id) WHERE state = 'queued' DO NOTHING
`

func (q *Queries) EnqueueCalendarSyncForSeller(ctx context.Context, sellerID string) error {
	_, err := q.db.Exec(ctx, enqueueCalendarSyncForSeller, sellerID)
	return err
}

const finishCalendarJob = `-- name: FinishCalendarJob :exec
UPDATE calendar_jobs SET state = $1, last_error = $2::text, claimed_at = NULL, updated_at = now(),
  due_at = CASE WHEN $1 = 'queued' THEN now() + make_interval(secs => $3::int) ELSE due_at END
WHERE id = $4::uuid
`

type FinishCalendarJobParams struct {
	State        string
	LastError    *string
	RetrySeconds int32
	ID           string
}

func (q *Queries) FinishCalendarJob(ctx context.Context, arg FinishCalendarJobParams) error {
	_, err := q.db.Exec(ctx, finishCalendarJob,
		arg.State,
		arg.LastError,
		arg.RetrySeconds,
		arg.ID,
	)
	return err
}

const insertBusyBlock = `-- name: InsertBusyBlock :exec
INSERT INTO calendar_busy_blocks(seller_id, busy)
VALUES ($1::uuid, tstzrange($2::timestamptz, $3::timestamptz, '[)'))
`

type InsertBusyBlockParams struct {
	SellerID string
	StartsAt time.Time
	EndsAt   time.Time
}

func (q *Queries) InsertBusyBlock(ctx context.Context, arg InsertBusyBlockParams) error {
	_, err := q.db.Exec(ctx, insertBusyBlock, arg.SellerID, arg.StartsAt, arg.EndsAt)
	return err
}

const markCalendarConnectionProblem = `-- name: MarkCalendarConnectionProblem :exec
UPDATE calendar_connections SET status = $1, last_error = $2::text, updated_at = now()
WHERE seller_id = $3::uuid
`

type MarkCalendarConnectionProblemParams struct {
	Status    string
	LastError string
	SellerID  string
}

func (q *Queries) MarkCalendarConnectionProblem(ctx context.Context, arg MarkCalendarConnectionProblemParams) error {
	_, err := q.db.Exec(ctx, markCalendarConnectionProblem, arg.Status, arg.LastError, arg.SellerID)
	return err
}

const markCalendarSynced = `-- name: MarkCalendarSynced :exec
UPDATE calendar_connections SET last_synced_at = now(), status = 'active', last_error = NULL, updated_at = now()
WHERE seller_id = $1::uuid AND status <> 'revoked'
`

func (q *Queries) MarkCalendarSynced(ctx context.Context, sellerID string) error {
	_, err := q.db.Exec(ctx, markCalendarSynced, sellerID)
	return err
}

const pruneOAuthStates = `-- name: PruneOAuthStates :exec
DELETE FROM oauth_states WHERE expires_at < now() - interval '1 hour'
`

func (q *Queries) PruneOAuthStates(ctx context.Context) error {
	_, err := q.db.Exec(ctx, pruneOAuthStates)
	return err
}

const saveCalendarConnection = `-- name: SaveCalendarConnection :exec
INSERT INTO calendar_connections(seller_id, account_email, encrypted_refresh_token, scopes)
VALUES ($1::uuid, $2, $3, $4)
ON CONFLICT (seller_id) DO UPDATE SET account_email = EXCLUDED.account_email, encrypted_refresh_token = EXCLUDED.encrypted_refresh_token,
  scopes = EXCLUDED.scopes, status = 'active', last_error = NULL, last_synced_at = NULL, connected_at = now(), updated_at = now()
`

type SaveCalendarConnectionParams struct {
	SellerID              string
	AccountEmail          string
	EncryptedRefreshToken []byte
	Scopes                string
}

func (q *Queries) SaveCalendarConnection(ctx context.Context, arg SaveCalendarConnectionParams) error {
	_, err := q.db.Exec(ctx, saveCalendarConnection,
		arg.SellerID,
		arg.AccountEmail,
		arg.EncryptedRefreshToken,
		arg.Scopes,
	)
	return err
}

const sellerForBusyRefresh = `-- name: SellerForBusyRefresh :one
SELECT c.seller_id::text AS seller_id, sp.booking_horizon_days,
       (c.last_synced_at IS NULL OR c.last_synced_at < now() - make_interval(secs => $1::int))::boolean AS stale
FROM calendar_connections c JOIN seller_profiles sp ON sp.id = c.seller_id
WHERE sp.id = $2::uuid AND c.status IN ('active', 'error') AND c.check_busy
`

type SellerForBusyRefreshParams struct {
	MaxAgeSeconds int32
	SellerID      string
}

type SellerForBusyRefreshRow struct {
	SellerID           string
	BookingHorizonDays int16
	Stale              bool
}

func (q *Queries) SellerForBusyRefresh(ctx context.Context, arg SellerForBusyRefreshParams) (SellerForBusyRefreshRow, error) {
	row := q.db.QueryRow(ctx, sellerForBusyRefresh, arg.MaxAgeSeconds, arg.SellerID)
	var i SellerForBusyRefreshRow
	err := row.Scan(&i.SellerID, &i.BookingHorizonDays, &i.Stale)
	return i, err
}

const sellerIDForHandle = `-- name: SellerIDForHandle :one
SELECT id::text FROM seller_profiles WHERE handle = $1
`

func (q *Queries) SellerIDForHandle(ctx context.Context, handle string) (string, error) {
	row := q.db.QueryRow(ctx, sellerIDForHandle, handle)
	var id string
	err := row.Scan(&id)
	return id, err
}

const sellerIDForUser = `-- name: SellerIDForUser :one
SELECT id::text FROM seller_profiles WHERE user_id = $1::uuid
`

func (q *Queries) SellerIDForUser(ctx context.Context, userID string) (string, error) {
	row := q.db.QueryRow(ctx, sellerIDForUser, userID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const setBookingCalendarEvent = `-- name: SetBookingCalendarEvent :exec
UPDATE bookings SET calendar_event_id = $1::text WHERE id = $2::uuid
`

type SetBookingCalendarEventParams struct {
	EventID   *string
	BookingID string
}

func (q *Queries) SetBookingCalendarEvent(ctx context.Context, arg SetBookingCalendarEventParams) error {
	_, err := q.db.Exec(ctx, setBookingCalendarEvent, arg.EventID, arg.BookingID)
	return err
}

const setBookingMeetLink = `-- name: SetBookingMeetLink :execrows
UPDATE bookings SET meeting_url = $1, meeting_ready_at = now(), meeting_source = 'google_meet'
WHERE id = $2::uuid AND meeting_url IS NULL AND state = 'confirmed' AND starts_at > now()
`

type SetBookingMeetLinkParams struct {
	MeetingUrl []byte
	BookingID  string
}

func (q *Queries) SetBookingMeetLink(ctx context.Context, arg SetBookingMeetLinkParams) (int64, error) {
	result, err := q.db.Exec(ctx, setBookingMeetLink, arg.MeetingUrl, arg.BookingID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateCalendarPreferences = `-- name: UpdateCalendarPreferences :exec
UPDATE calendar_connections SET check_busy = $1, add_events = $2, create_meet_links = $3, updated_at = now()
WHERE seller_id = $4::uuid
`

type UpdateCalendarPreferencesParams struct {
	CheckBusy       bool
	AddEvents       bool
	CreateMeetLinks bool
	SellerID        string
}

func (q *Queries) UpdateCalendarPreferences(ctx context.Context, arg UpdateCalendarPreferencesParams) error {
	_, err := q.db.Exec(ctx, updateCalendarPreferences,
		arg.CheckBusy,
		arg.AddEvents,
		arg.CreateMeetLinks,
		arg.SellerID,
	)
	return err
}
