// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: holds.sql

package store

import (
	"context"
	"time"
)

const countBuyerActiveHolds = `-- name: CountBuyerActiveHolds :one
SELECT count(*) FROM quotes q JOIN slot_reservations sr ON sr.quote_id = q.id
WHERE q.buyer_user_id = $1 AND q.state = 'held' AND sr.active AND sr.reservation_kind = 'hold' AND sr.expires_at > now()
`

func (q *Queries) CountBuyerActiveHolds(ctx context.Context, buyerUserID string) (int64, error) {
	row := q.db.QueryRow(ctx, countBuyerActiveHolds, buyerUserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const extendOfferCheckoutWindow = `-- name: ExtendOfferCheckoutWindow :exec
UPDATE offers SET checkout_expires_at = GREATEST(checkout_expires_at, $1::timestamptz)
WHERE id = $2 AND state = 'agreed'
`

type ExtendOfferCheckoutWindowParams struct {
	Until time.Time
	ID    string
}

func (q *Queries) ExtendOfferCheckoutWindow(ctx context.Context, arg ExtendOfferCheckoutWindowParams) error {
	_, err := q.db.Exec(ctx, extendOfferCheckoutWindow, arg.Until, arg.ID)
	return err
}

const extendQuoteHold = `-- name: ExtendQuoteHold :one
UPDATE quotes SET expires_at = GREATEST(expires_at, $1::timestamptz)
WHERE id = $2 AND state = 'held' AND expires_at > now()
RETURNING offer_id
`

type ExtendQuoteHoldParams struct {
	Until time.Time
	ID    string
}

func (q *Queries) ExtendQuoteHold(ctx context.Context, arg ExtendQuoteHoldParams) (*string, error) {
	row := q.db.QueryRow(ctx, extendQuoteHold, arg.Until, arg.ID)
	var offer_id *string
	err := row.Scan(&offer_id)
	return offer_id, err
}

const extendSlotHold = `-- name: ExtendSlotHold :execrows
UPDATE slot_reservations SET expires_at = GREATEST(expires_at, $1::timestamptz)
WHERE quote_id = $2::uuid AND active AND reservation_kind = 'hold' AND expires_at > now()
`

type ExtendSlotHoldParams struct {
	Until   time.Time
	QuoteID string
}

func (q *Queries) ExtendSlotHold(ctx context.Context, arg ExtendSlotHoldParams) (int64, error) {
	result, err := q.db.Exec(ctx, extendSlotHold, arg.Until, arg.QuoteID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const releaseBuyerUnpaidHoldsWithSeller = `-- name: ReleaseBuyerUnpaidHoldsWithSeller :exec
WITH released AS (
  UPDATE slot_reservations sr SET active = false FROM quotes q
  WHERE sr.quote_id = q.id AND q.buyer_user_id = $1::uuid AND q.seller_id = $2::uuid AND q.state = 'held'
    AND sr.active AND sr.reservation_kind = 'hold'
    AND NOT EXISTS (SELECT 1 FROM payment_attempts p WHERE p.quote_id = q.id)
  RETURNING q.id
)
UPDATE quotes SET state = 'expired' FROM released WHERE quotes.id = released.id
`

type ReleaseBuyerUnpaidHoldsWithSellerParams struct {
	BuyerUserID string
	SellerID    string
}

func (q *Queries) ReleaseBuyerUnpaidHoldsWithSeller(ctx context.Context, arg ReleaseBuyerUnpaidHoldsWithSellerParams) error {
	_, err := q.db.Exec(ctx, releaseBuyerUnpaidHoldsWithSeller, arg.BuyerUserID, arg.SellerID)
	return err
}

const releaseExpiredHolds = `-- name: ReleaseExpiredHolds :exec
WITH released AS (
  UPDATE slot_reservations sr SET active = false
  WHERE sr.seller_id = $1::uuid AND sr.active AND sr.reservation_kind = 'hold' AND sr.expires_at <= now()
    AND sr.occupied_range && tstzrange($2::timestamptz, $3::timestamptz, '[)')
  RETURNING sr.quote_id
)
UPDATE quotes q SET state = 'expired' FROM released WHERE q.id = released.quote_id AND q.state = 'held'
`

type ReleaseExpiredHoldsParams struct {
	SellerID  string
	RangeFrom time.Time
	RangeTo   time.Time
}

func (q *Queries) ReleaseExpiredHolds(ctx context.Context, arg ReleaseExpiredHoldsParams) error {
	_, err := q.db.Exec(ctx, releaseExpiredHolds, arg.SellerID, arg.RangeFrom, arg.RangeTo)
	return err
}
