// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ledger.sql

package store

import (
	"context"
)

const findLedgerAccount = `-- name: FindLedgerAccount :one
SELECT id FROM ledger_accounts
WHERE account_code = $1 AND currency = $2
  AND COALESCE(scope_id, '00000000-0000-0000-0000-000000000000'::uuid) = COALESCE($3::uuid, '00000000-0000-0000-0000-000000000000'::uuid)
`

type FindLedgerAccountParams struct {
	AccountCode string
	Currency    string
	ScopeID     *string
}

func (q *Queries) FindLedgerAccount(ctx context.Context, arg FindLedgerAccountParams) (string, error) {
	row := q.db.QueryRow(ctx, findLedgerAccount, arg.AccountCode, arg.Currency, arg.ScopeID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const insertLedgerAccount = `-- name: InsertLedgerAccount :one
INSERT INTO ledger_accounts(account_code, currency, scope_id)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
RETURNING id
`

type InsertLedgerAccountParams struct {
	AccountCode string
	Currency    string
	ScopeID     *string
}

func (q *Queries) InsertLedgerAccount(ctx context.Context, arg InsertLedgerAccountParams) (string, error) {
	row := q.db.QueryRow(ctx, insertLedgerAccount, arg.AccountCode, arg.Currency, arg.ScopeID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const insertLedgerEntry = `-- name: InsertLedgerEntry :exec
INSERT INTO ledger_entries(journal_id, account_id, side, amount_minor)
VALUES ($1, $2, $3, $4)
`

type InsertLedgerEntryParams struct {
	JournalID   string
	AccountID   string
	Side        string
	AmountMinor int64
}

func (q *Queries) InsertLedgerEntry(ctx context.Context, arg InsertLedgerEntryParams) error {
	_, err := q.db.Exec(ctx, insertLedgerEntry,
		arg.JournalID,
		arg.AccountID,
		arg.Side,
		arg.AmountMinor,
	)
	return err
}

const insertLedgerJournal = `-- name: InsertLedgerJournal :one
INSERT INTO ledger_journals(source_type, source_id, currency, description, request_digest)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (source_type, source_id) DO NOTHING
RETURNING id
`

type InsertLedgerJournalParams struct {
	SourceType    string
	SourceID      string
	Currency      string
	Description   string
	RequestDigest []byte
}

func (q *Queries) InsertLedgerJournal(ctx context.Context, arg InsertLedgerJournalParams) (string, error) {
	row := q.db.QueryRow(ctx, insertLedgerJournal,
		arg.SourceType,
		arg.SourceID,
		arg.Currency,
		arg.Description,
		arg.RequestDigest,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const ledgerJournalBySource = `-- name: LedgerJournalBySource :one
SELECT id, request_digest FROM ledger_journals WHERE source_type = $1 AND source_id = $2
`

type LedgerJournalBySourceParams struct {
	SourceType string
	SourceID   string
}

type LedgerJournalBySourceRow struct {
	ID            string
	RequestDigest []byte
}

func (q *Queries) LedgerJournalBySource(ctx context.Context, arg LedgerJournalBySourceParams) (LedgerJournalBySourceRow, error) {
	row := q.db.QueryRow(ctx, ledgerJournalBySource, arg.SourceType, arg.SourceID)
	var i LedgerJournalBySourceRow
	err := row.Scan(&i.ID, &i.RequestDigest)
	return i, err
}
