// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type AdminGrant struct {
	ID         string
	UserID     string
	Permission string
	GrantedBy  string
	GrantedAt  time.Time
	RevokedAt  *time.Time
}

type AdminMfa struct {
	UserID          string
	EncryptedSecret []byte
	FailedAttempts  int16
	LockedUntil     *time.Time
	UpdatedAt       time.Time
	LastTotpStep    *int64
}

type AuditEvent struct {
	ID          string
	ActorID     *string
	Action      string
	TargetID    *string
	Reason      *string
	SafeSummary []byte
	CreatedAt   time.Time
}

type AvailabilityOverride struct {
	ID                 string
	SellerID           string
	LocalDate          pgtype.Date
	Closed             bool
	ReplacementWindows []byte
}

type AvailabilityWindow struct {
	ID         string
	SellerID   string
	Weekday    int16
	LocalStart pgtype.Time
	LocalEnd   pgtype.Time
	Timezone   string
}

type Booking struct {
	ID                  string
	QuoteID             *string
	SellerID            string
	BuyerUserID         string
	BuyerName           string
	GuestEmail          string
	DurationMinutes     int32
	StartsAt            time.Time
	GrossMinor          int64
	Currency            string
	State               string
	PaymentState        string
	QuoteSnapshot       []byte
	MeetingUrl          []byte
	MeetingDeadline     time.Time
	MeetingReadyAt      *time.Time
	IssueReason         *string
	IssueCreatedAt      *time.Time
	IssueResolvedAt     *time.Time
	BuyerCompletedAt    *time.Time
	SellerCompletedAt   *time.Time
	CreatedAt           time.Time
	CalendarSequence    int32
	CalendarEventID     *string
	MeetingSource       *string
	CancelledAt         *time.Time
	CancelledByRole     *string
	CancellationReason  *string
	IssueReportedBy     *string
	IssueResolution     *string
	IssueRespondBy      *time.Time
	IssueSellerResponse *string
	IssueDisputedAt     *time.Time
	IssueSellerNote     *string
}

type BookingCancellationRequest struct {
	ID              string
	BookingID       string
	RequesterUserID string
	Reason          string
	State           string
	Resolution      *string
	CreatedAt       time.Time
	ResolvedAt      *time.Time
}

type Broadcast struct {
	ID          string
	Subject     string
	Heading     string
	Body        string
	ActionLabel *string
	ActionUrl   *string
	State       string
	CreatedBy   string
	CreatedAt   time.Time
	QueuedAt    *time.Time
	FinishedAt  *time.Time
	ImageUrl    *string
}

type BroadcastDelivery struct {
	BroadcastID string
	Email       string
	State       string
	Attempts    int32
	SentAt      *time.Time
}

type CalendarBusyBlock struct {
	SellerID string
	Busy     pgtype.Range[pgtype.Timestamptz]
	SyncedAt time.Time
}

type CalendarConnection struct {
	SellerID              string
	Provider              string
	AccountEmail          string
	EncryptedRefreshToken []byte
	Scopes                string
	CheckBusy             bool
	AddEvents             bool
	CreateMeetLinks       bool
	Status                string
	LastError             *string
	LastSyncedAt          *time.Time
	ConnectedAt           time.Time
	UpdatedAt             time.Time
}

type CalendarJob struct {
	ID        string
	BookingID string
	State     string
	Attempts  int16
	DueAt     time.Time
	ClaimedAt *time.Time
	LastError *string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type DataRequest struct {
	ID        string
	UserID    string
	Kind      string
	CreatedAt time.Time
}

type EmailChallenge struct {
	ID              string
	NormalizedEmail string
	Purpose         string
	CodeHash        []byte
	ExpiresAt       time.Time
	Attempts        int16
	ConsumedAt      *time.Time
	CreatedAt       time.Time
}

type GrowthRelationship struct {
	ID                  string
	SourceUserID        string
	ChildUserID         string
	QualifyingBookingID *string
	AttributionMethod   string
	AttributedAt        time.Time
}

type HandleHold struct {
	Handle    string
	HeldUntil time.Time
	CreatedAt time.Time
}

type HandleRedirect struct {
	OldHandle string
	SellerID  string
	CreatedAt time.Time
}

type IdempotencyRecord struct {
	ID             string
	ActorScope     string
	Operation      string
	IdempotencyKey string
	RequestDigest  []byte
	ResponseStatus *int32
	ResponseBody   []byte
	CreatedAt      time.Time
}

type LedgerAccount struct {
	ID          string
	AccountCode string
	Currency    string
	ScopeID     *string
	CreatedAt   time.Time
}

type LedgerEntry struct {
	ID          string
	JournalID   string
	AccountID   string
	Side        string
	AmountMinor int64
	CreatedAt   time.Time
}

type LedgerJournal struct {
	ID            string
	SourceType    string
	SourceID      string
	Currency      string
	Description   string
	RequestDigest []byte
	CreatedAt     time.Time
}

type MarketingConsentEvent struct {
	ID         string
	Email      string
	Subscribed bool
	Source     string
	Wording    string
	CreatedAt  time.Time
}

type MarketingContact struct {
	Email            string
	UserID           *string
	Subscribed       bool
	Source           string
	Wording          string
	ConfirmedAt      *time.Time
	UnsubscribeToken string
	ConsentedAt      *time.Time
	UnsubscribedAt   *time.Time
	UpdatedAt        time.Time
}

type NoShowReport struct {
	ID             string
	BookingID      string
	ReporterUserID string
	AbsentRole     string
	State          string
	DisputeReason  *string
	ResolvesAt     time.Time
	Resolution     *string
	ResolvedBy     *string
	CreatedAt      time.Time
	ResolvedAt     *time.Time
}

type NotificationOutbox struct {
	ID                 string
	EventKey           string
	BookingID          *string
	RecipientUserID    string
	Kind               string
	DueAt              time.Time
	State              string
	Attempts           int16
	ClaimedAt          *time.Time
	SentAt             *time.Time
	LastErrorCode      *string
	CreatedAt          time.Time
	OfferID            *string
	ReferenceID        *string
	PaymentExceptionID *string
	AutoRetries        int32
}

type OauthState struct {
	StateHash    []byte
	UserID       string
	CodeVerifier string
	ExpiresAt    time.Time
	CreatedAt    time.Time
}

type Offer struct {
	ID                 string
	SellerID           string
	BuyerUserID        string
	BuyerName          string
	BuyerEmail         string
	DurationMinutes    int32
	State              string
	Version            int32
	ExpiresAt          time.Time
	CheckoutExpiresAt  *time.Time
	IdempotencyKey     string
	RequestDigest      []byte
	CreatedAt          time.Time
	ConvertedBookingID *string
}

type OfferVersion struct {
	ID          string
	OfferID     string
	Version     int32
	AmountMinor int64
	Actor       string
	CreatedAt   time.Time
}

type OpsAlert struct {
	Key            string
	State          string
	Severity       string
	Summary        string
	Value          float64
	FirstFiredAt   time.Time
	LastNotifiedAt *time.Time
	ResolvedAt     *time.Time
	UpdatedAt      time.Time
}

type OutboxJob struct {
	ID            string
	JobType       string
	DedupeKey     string
	PayloadRef    []byte
	RunAt         time.Time
	LeasedUntil   *time.Time
	Attempts      int32
	CompletedAt   *time.Time
	LastErrorCode *string
}

type PaymentAllocation struct {
	ID                      string
	BookingID               string
	GrossMinor              int64
	DeductionMinor          int64
	SellerEntitlementMinor  int64
	ProcessorCostMinor      int64
	SettlementRoute         string
	SettlementRouteSnapshot []byte
	FeeBasisPoints          int32
}

type PaymentAttempt struct {
	ID                    string
	BookingID             *string
	Provider              string
	Environment           string
	MerchantReference     string
	ExpectedMinor         int64
	Currency              string
	CanonicalState        string
	ProviderTransactionID *string
	QuoteID               *string
	AuthorizationUrl      *string
	AccessCode            *string
	CreatedAt             time.Time
	UpdatedAt             time.Time
	LastVerifiedAt        *time.Time
	ApprovedFeeMinor      *int64
	FeeBasisPoints        *int32
	CardCountry           *string
	CardBrand             *string
	Channel               *string
	TransferDetails       []byte
	InstructionsExpireAt  *time.Time
	PaidMinor             *int64
	BuyerFeeMinor         int64
}

type PaymentException struct {
	ID                    string
	BookingID             *string
	PaymentAttemptID      *string
	Kind                  string
	State                 string
	ProviderCaseReference *string
	ProviderDeadline      *time.Time
	AmountMinor           *int64
	Currency              *string
	Reason                string
	Evidence              []byte
	Resolution            *string
	CreatedAt             time.Time
	ResolvedAt            *time.Time
}

type PricingVersion struct {
	ID             string
	SellerID       string
	Currency       string
	Base30Minor    int64
	Durations      []int32
	FeeBasisPoints int16
	CreatedAt      time.Time
}

type ProductEvent struct {
	ID          string
	EventName   string
	SubjectHash []byte
	Environment string
	Props       []byte
	OccurredAt  time.Time
	ReceivedAt  time.Time
	SellerID    *string
	EventDay    pgtype.Date
}

type ProviderCase struct {
	ID                string
	Provider          string
	Environment       string
	ProviderCaseID    string
	PaymentAttemptID  *string
	ProviderReference string
	CaseType          string
	State             string
	AmountMinor       *int64
	Currency          *string
	ProviderDeadline  *time.Time
	LastEventType     string
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type ProviderEvent struct {
	ID                 string
	Provider           string
	Environment        string
	EventDigest        []byte
	RawBodyHash        []byte
	State              string
	ReceivedAt         time.Time
	EventType          *string
	ProviderReference  *string
	ProcessingAttempts int32
	LastErrorCode      *string
	MinimalPayload     []byte
	NextAttemptAt      time.Time
	ClaimedAt          *time.Time
	AutoRetries        int32
}

type ProviderFeeSchedule struct {
	ID            string
	Provider      string
	Currency      string
	Channel       string
	PercentBps    int32
	FixedMinor    int64
	CapMinor      *int64
	EffectiveFrom time.Time
	ApprovedAt    *time.Time
	ApprovedBy    *string
}

type PushOutbox struct {
	ID        string
	EventKey  string
	UserID    string
	BookingID string
	Kind      string
	State     string
	Attempts  int32
	DueAt     time.Time
	CreatedAt time.Time
	SentAt    *time.Time
}

type PushSubscription struct {
	ID            string
	UserID        string
	Endpoint      string
	P256dh        string
	Auth          string
	CreatedAt     time.Time
	LastSuccessAt *time.Time
	Failures      int32
}

type Quote struct {
	ID               string
	SellerID         string
	BuyerUserID      string
	PricingVersionID string
	BuyerName        string
	DurationMinutes  int32
	StartsAt         time.Time
	GrossMinor       int64
	Currency         string
	State            string
	ExpiresAt        time.Time
	IdempotencyKey   string
	RequestDigest    []byte
	CreatedAt        time.Time
	OfferID          *string
}

type Refund struct {
	ID                 string
	BookingID          *string
	PaymentAttemptID   *string
	AmountMinor        int64
	Currency           string
	PlatformShareMinor int64
	SellerShareMinor   int64
	Reason             string
	State              string
	ProviderRefundID   *string
	Attempts           int16
	NextAttemptAt      time.Time
	LastError          *string
	RequestedBy        *string
	ApprovedBy         *string
	Note               *string
	CreatedAt          time.Time
	SubmittedAt        *time.Time
	ProcessedAt        *time.Time
	UpdatedAt          time.Time
	SellerLiability    string
	PaymentExceptionID *string
	AutoRetries        int32
}

type RescheduleEvent struct {
	ID               string
	RequestID        string
	ActorUserID      string
	Action           string
	PreviousStartsAt time.Time
	ProposedStartsAt time.Time
	CreatedAt        time.Time
}

type RescheduleRequest struct {
	ID               string
	BookingID        string
	RequesterUserID  string
	ProposedStartsAt time.Time
	State            string
	Version          int32
	ExpiresAt        time.Time
	RespondedBy      *string
	RespondedAt      *time.Time
	CreatedAt        time.Time
}

type Review struct {
	ID           string
	BookingID    string
	SellerID     string
	BuyerUserID  string
	ReviewerName string
	Rating       int16
	Body         string
	SellerReply  *string
	RepliedAt    *time.Time
	HiddenAt     *time.Time
	HiddenReason *string
	CreatedAt    time.Time
}

type SellerPayout struct {
	ID                   string
	BookingID            string
	SellerID             string
	Provider             string
	EntitlementMinor     int64
	AmountMinor          *int64
	RecoveryMinor        int64
	FeeMinor             int64
	Currency             string
	State                string
	Reference            string
	BankCode             *string
	AccountSealed        []byte
	AccountName          *string
	AccountLast4         *string
	BankName             *string
	ProviderTransferCode *string
	FundsAvailableAt     time.Time
	Attempts             int32
	Generation           int32
	NextAttemptAt        time.Time
	LastError            *string
	ReleasedAt           *time.Time
	PaidAt               *time.Time
	CreatedAt            time.Time
	UpdatedAt            time.Time
	DestinationType      string
}

type SellerPayoutAccount struct {
	SellerID           string
	Provider           string
	Country            string
	BankCode           string
	BankName           string
	AccountLast4       string
	AccountName        string
	AccountSealed      []byte
	AccountFingerprint string
	Currency           string
	VerifiedAt         time.Time
	UsableFrom         time.Time
	UpdatedAt          time.Time
	DestinationType    string
}

type SellerProfile struct {
	ID                   string
	UserID               string
	Handle               string
	Mode                 string
	PublicationState     string
	ReadinessState       string
	Timezone             string
	MinimumNoticeMinutes int16
	BookingHorizonDays   int16
	BufferMinutes        int16
	Paused               bool
	CreatedAt            time.Time
	IdentityUrl          *string
	AvatarMime           *string
	AvatarData           []byte
	AvatarVersion        int64
	PublicVersion        int64
	AvatarKey            *string
	Country              string
	Currency             string
	HandleChangedAt      *time.Time
	HandleReminderDue    *time.Time
}

type SellerRecovery struct {
	ID             string
	SellerID       string
	RefundID       string
	AmountMinor    int64
	RecoveredMinor int64
	Currency       string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type Session struct {
	ID            string
	TokenHash     []byte
	UserID        *string
	GuestScope    []byte
	ExpiresAt     time.Time
	MfaVerifiedAt *time.Time
	RevokedAt     *time.Time
	CreatedAt     time.Time
}

type SettlementConfirmation struct {
	ID                  string
	SettlementItemID    string
	AmountMinor         int64
	ConfirmedAt         time.Time
	Source              string
	ReconciliationState string
}

type SettlementImportRow struct {
	ID                  string
	ImportID            string
	Provider            string
	Environment         string
	ProviderReference   string
	SettlementReference *string
	AmountMinor         int64
	Currency            string
	SettledAt           time.Time
	ReconciliationState string
	SettlementItemID    *string
	ReceivedAt          time.Time
}

type SettlementItem struct {
	ID                string
	AllocationID      string
	Route             string
	State             string
	ProviderReference *string
}

type SlotReservation struct {
	ID              string
	SellerID        string
	OccupiedFrom    time.Time
	OccupiedTo      time.Time
	OccupiedRange   pgtype.Range[pgtype.Timestamptz]
	Active          bool
	ReservationKind string
	QuoteID         *string
	ExpiresAt       *time.Time
	BookingID       *string
}

type User struct {
	ID          string
	DisplayName string
	Status      string
	Timezone    string
	CreatedAt   time.Time
	DeletedAt   *time.Time
}

type UserIdentity struct {
	ID                   string
	UserID               string
	Type                 string
	NormalizedIdentifier string
	VerifiedAt           *time.Time
}

type WorkerHeartbeat struct {
	Name        string
	Instance    string
	LastBeatAt  time.Time
	LastErrorAt *time.Time
	LastError   *string
}
