// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notifications.sql

package store

import (
	"context"
	"time"
)

const bookingParticipants = `-- name: BookingParticipants :one
SELECT b.buyer_user_id, sp.user_id AS seller_user_id, b.starts_at
FROM bookings b JOIN seller_profiles sp ON sp.id = b.seller_id
WHERE b.id = $1
`

type BookingParticipantsRow struct {
	BuyerUserID  string
	SellerUserID string
	StartsAt     time.Time
}

func (q *Queries) BookingParticipants(ctx context.Context, bookingID string) (BookingParticipantsRow, error) {
	row := q.db.QueryRow(ctx, bookingParticipants, bookingID)
	var i BookingParticipantsRow
	err := row.Scan(&i.BuyerUserID, &i.SellerUserID, &i.StartsAt)
	return i, err
}

const cancelPendingBookingReminders = `-- name: CancelPendingBookingReminders :exec
UPDATE notification_outbox SET state = 'cancelled', claimed_at = NULL, last_error_code = $1::text
WHERE booking_id = $2::uuid AND state IN ('queued', 'processing')
  AND (kind LIKE 'booking_reminder_%' OR kind LIKE 'meeting_link_due_%' OR kind = 'review_request_buyer')
`

type CancelPendingBookingRemindersParams struct {
	ReasonCode string
	BookingID  string
}

func (q *Queries) CancelPendingBookingReminders(ctx context.Context, arg CancelPendingBookingRemindersParams) error {
	_, err := q.db.Exec(ctx, cancelPendingBookingReminders, arg.ReasonCode, arg.BookingID)
	return err
}

const claimDueNotifications = `-- name: ClaimDueNotifications :many
WITH claimable AS (
  SELECT id FROM notification_outbox
  WHERE attempts < 8 AND ((state = 'queued' AND due_at <= now()) OR (state = 'processing' AND claimed_at < now() - interval '5 minutes'))
  ORDER BY due_at, id
  FOR UPDATE SKIP LOCKED
  LIMIT $1::int
)
UPDATE notification_outbox n SET state = 'processing', claimed_at = now(), attempts = n.attempts + 1
FROM claimable c WHERE n.id = c.id
RETURNING n.id
`

func (q *Queries) ClaimDueNotifications(ctx context.Context, batchSize int32) ([]string, error) {
	rows, err := q.db.Query(ctx, claimDueNotifications, batchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const enqueueCancellationReview = `-- name: EnqueueCancellationReview :exec
INSERT INTO notification_outbox(id, event_key, booking_id, recipient_user_id, kind, due_at)
SELECT gen_random_uuid(), $1::text || ':cancellation-review:' || recipient.role, b.id, recipient.user_id, recipient.kind, now()
FROM booking_cancellation_requests cr
JOIN bookings b ON b.id = cr.booking_id
JOIN seller_profiles sp ON sp.id = b.seller_id
CROSS JOIN LATERAL (VALUES ('buyer', b.buyer_user_id, 'cancellation_reviewed_buyer'), ('seller', sp.user_id, 'cancellation_reviewed_seller')) AS recipient(role, user_id, kind)
WHERE cr.id = $1::uuid AND recipient.user_id IS NOT NULL
ON CONFLICT (event_key) DO NOTHING
`

func (q *Queries) EnqueueCancellationReview(ctx context.Context, cancellationID string) error {
	_, err := q.db.Exec(ctx, enqueueCancellationReview, cancellationID)
	return err
}

const enqueueMeetingReady = `-- name: EnqueueMeetingReady :exec
INSERT INTO notification_outbox(id, event_key, booking_id, recipient_user_id, kind, due_at)
SELECT gen_random_uuid(), b.id::text || ':meeting-link-ready:' || b.meeting_ready_at::text, b.id, b.buyer_user_id, 'meeting_link_ready_buyer', now()
FROM bookings b WHERE b.id = $1::uuid
ON CONFLICT (event_key) DO NOTHING
`

func (q *Queries) EnqueueMeetingReady(ctx context.Context, bookingID string) error {
	_, err := q.db.Exec(ctx, enqueueMeetingReady, bookingID)
	return err
}

const enqueueNotification = `-- name: EnqueueNotification :exec
INSERT INTO notification_outbox(id, event_key, booking_id, recipient_user_id, kind, due_at, reference_id)
VALUES (gen_random_uuid(), $1, $2::uuid, $3, $4, $5, $6::uuid)
ON CONFLICT (event_key) DO NOTHING
`

type EnqueueNotificationParams struct {
	EventKey        string
	BookingID       string
	RecipientUserID string
	Kind            string
	DueAt           time.Time
	ReferenceID     *string
}

func (q *Queries) EnqueueNotification(ctx context.Context, arg EnqueueNotificationParams) error {
	_, err := q.db.Exec(ctx, enqueueNotification,
		arg.EventKey,
		arg.BookingID,
		arg.RecipientUserID,
		arg.Kind,
		arg.DueAt,
		arg.ReferenceID,
	)
	return err
}

const enqueueOfferNotification = `-- name: EnqueueOfferNotification :exec
INSERT INTO notification_outbox(id, event_key, offer_id, recipient_user_id, kind, due_at)
VALUES (gen_random_uuid(), $1, $2::uuid, $3::uuid, $4, now())
ON CONFLICT (event_key) DO NOTHING
`

type EnqueueOfferNotificationParams struct {
	EventKey        string
	OfferID         string
	RecipientUserID string
	Kind            string
}

func (q *Queries) EnqueueOfferNotification(ctx context.Context, arg EnqueueOfferNotificationParams) error {
	_, err := q.db.Exec(ctx, enqueueOfferNotification,
		arg.EventKey,
		arg.OfferID,
		arg.RecipientUserID,
		arg.Kind,
	)
	return err
}

const enqueueRescheduleEmails = `-- name: EnqueueRescheduleEmails :exec
INSERT INTO notification_outbox(id, event_key, booking_id, recipient_user_id, kind, due_at)
SELECT gen_random_uuid(), $1::text || ':reschedule:' || recipient.role, b.id, recipient.user_id, recipient.kind, now()
FROM bookings b
JOIN seller_profiles sp ON sp.id = b.seller_id
CROSS JOIN LATERAL (VALUES ('buyer', b.buyer_user_id, 'reschedule_accepted_buyer'), ('seller', sp.user_id, 'reschedule_accepted_seller')) AS recipient(role, user_id, kind)
WHERE b.id = $2::uuid
ON CONFLICT (event_key) DO NOTHING
`

type EnqueueRescheduleEmailsParams struct {
	RequestID string
	BookingID string
}

func (q *Queries) EnqueueRescheduleEmails(ctx context.Context, arg EnqueueRescheduleEmailsParams) error {
	_, err := q.db.Exec(ctx, enqueueRescheduleEmails, arg.RequestID, arg.BookingID)
	return err
}

const failExhaustedNotifications = `-- name: FailExhaustedNotifications :exec
UPDATE notification_outbox SET state = 'failed', claimed_at = NULL, last_error_code = 'RETRY_LIMIT'
WHERE attempts >= 8 AND state IN ('queued', 'processing')
`

func (q *Queries) FailExhaustedNotifications(ctx context.Context) error {
	_, err := q.db.Exec(ctx, failExhaustedNotifications)
	return err
}

const markNotificationCancelled = `-- name: MarkNotificationCancelled :exec
UPDATE notification_outbox SET state = 'cancelled', claimed_at = NULL, last_error_code = 'STALE_BOOKING'
WHERE id = $1 AND state = 'processing'
`

func (q *Queries) MarkNotificationCancelled(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, markNotificationCancelled, id)
	return err
}

const markNotificationFailed = `-- name: MarkNotificationFailed :exec
UPDATE notification_outbox
SET state = CASE WHEN attempts >= 8 THEN 'failed' ELSE 'queued' END,
    due_at = now() + make_interval(secs => LEAST(3600, 30 * (2 ^ LEAST(attempts, 7))::int)),
    claimed_at = NULL, last_error_code = $1::text
WHERE id = $2 AND state = 'processing'
`

type MarkNotificationFailedParams struct {
	ErrorCode string
	ID        string
}

func (q *Queries) MarkNotificationFailed(ctx context.Context, arg MarkNotificationFailedParams) error {
	_, err := q.db.Exec(ctx, markNotificationFailed, arg.ErrorCode, arg.ID)
	return err
}

const markNotificationSent = `-- name: MarkNotificationSent :exec
UPDATE notification_outbox SET state = 'sent', sent_at = now(), claimed_at = NULL, last_error_code = NULL
WHERE id = $1 AND state = 'processing'
`

func (q *Queries) MarkNotificationSent(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, markNotificationSent, id)
	return err
}

const notificationContext = `-- name: NotificationContext :one
SELECT n.kind, b.id AS booking_id, identity.normalized_identifier AS recipient_email, owner.display_name AS seller_name, b.buyer_name,
       sp.handle, sp.timezone, recipient.timezone AS recipient_timezone, (recipient.id = sp.user_id)::boolean AS recipient_is_seller,
       COALESCE(buyer.timezone, sp.timezone)::text AS buyer_timezone,
       b.state AS booking_state, b.payment_state, b.starts_at, b.duration_minutes, b.meeting_url, b.gross_minor, b.currency, b.calendar_sequence,
       COALESCE(pa.seller_entitlement_minor, 0)::bigint AS seller_entitlement_minor, (pa.id IS NOT NULL)::boolean AS has_allocation,
       rr.proposed_starts_at AS reschedule_starts_at, rr.expires_at AS reschedule_expires_at, COALESCE(rr.state, '')::text AS reschedule_state,
       COALESCE(b.cancelled_by_role, '')::text AS cancelled_by_role,
       COALESCE(rf.amount_minor, 0)::bigint AS refund_minor, COALESCE(rf.seller_share_minor, 0)::bigint AS refund_seller_share_minor, COALESCE(rf.state, '')::text AS refund_state, COALESCE(rf.seller_liability, '')::text AS refund_seller_liability,
       COALESCE(ns.absent_role, '')::text AS no_show_absent_role, COALESCE(ns.state, '')::text AS no_show_state, ns.resolves_at AS no_show_resolves_at,
       COALESCE(rv.rating, 0)::int AS review_rating, COALESCE(rv.body, '')::text AS review_body,
       EXISTS (SELECT 1 FROM reviews own WHERE own.booking_id = b.id)::boolean AS has_review,
       COALESCE(po.state, '')::text AS payout_state, COALESCE(po.amount_minor - po.recovery_minor, 0)::bigint AS payout_net_minor,
       COALESCE(po.recovery_minor, 0)::bigint AS payout_recovery_minor, COALESCE(po.bank_name, '')::text AS payout_bank_name,
       COALESCE(po.account_last4, '')::text AS payout_account_last4,
       COALESCE(b.issue_resolution, '')::text AS issue_resolution
FROM notification_outbox n
JOIN bookings b ON b.id = n.booking_id
LEFT JOIN users buyer ON buyer.id = b.buyer_user_id
LEFT JOIN reschedule_requests rr ON rr.id = n.reference_id AND rr.booking_id = b.id
LEFT JOIN refunds rf ON rf.id = n.reference_id AND rf.booking_id = b.id
LEFT JOIN no_show_reports ns ON ns.id = n.reference_id AND ns.booking_id = b.id
LEFT JOIN reviews rv ON rv.id = n.reference_id AND rv.booking_id = b.id
LEFT JOIN seller_payouts po ON po.id = n.reference_id AND po.booking_id = b.id
JOIN seller_profiles sp ON sp.id = b.seller_id
JOIN users owner ON owner.id = sp.user_id
JOIN users recipient ON recipient.id = n.recipient_user_id AND recipient.status = 'active'
JOIN user_identities identity ON identity.user_id = recipient.id AND identity.type = 'email'
LEFT JOIN payment_allocations pa ON pa.booking_id = b.id
WHERE n.id = $1 AND n.state = 'processing' AND (recipient.id = sp.user_id OR recipient.id = b.buyer_user_id)
LIMIT 1
`

type NotificationContextRow struct {
	Kind                   string
	BookingID              string
	RecipientEmail         string
	SellerName             string
	BuyerName              string
	Handle                 string
	Timezone               string
	RecipientTimezone      string
	RecipientIsSeller      bool
	BuyerTimezone          string
	BookingState           string
	PaymentState           string
	StartsAt               time.Time
	DurationMinutes        int32
	MeetingUrl             []byte
	GrossMinor             int64
	Currency               string
	CalendarSequence       int32
	SellerEntitlementMinor int64
	HasAllocation          bool
	RescheduleStartsAt     *time.Time
	RescheduleExpiresAt    *time.Time
	RescheduleState        string
	CancelledByRole        string
	RefundMinor            int64
	RefundSellerShareMinor int64
	RefundState            string
	RefundSellerLiability  string
	NoShowAbsentRole       string
	NoShowState            string
	NoShowResolvesAt       *time.Time
	ReviewRating           int32
	ReviewBody             string
	HasReview              bool
	PayoutState            string
	PayoutNetMinor         int64
	PayoutRecoveryMinor    int64
	PayoutBankName         string
	PayoutAccountLast4     string
	IssueResolution        string
}

// Buyers who paid without confirming their email still get their booking emails.
func (q *Queries) NotificationContext(ctx context.Context, id string) (NotificationContextRow, error) {
	row := q.db.QueryRow(ctx, notificationContext, id)
	var i NotificationContextRow
	err := row.Scan(
		&i.Kind,
		&i.BookingID,
		&i.RecipientEmail,
		&i.SellerName,
		&i.BuyerName,
		&i.Handle,
		&i.Timezone,
		&i.RecipientTimezone,
		&i.RecipientIsSeller,
		&i.BuyerTimezone,
		&i.BookingState,
		&i.PaymentState,
		&i.StartsAt,
		&i.DurationMinutes,
		&i.MeetingUrl,
		&i.GrossMinor,
		&i.Currency,
		&i.CalendarSequence,
		&i.SellerEntitlementMinor,
		&i.HasAllocation,
		&i.RescheduleStartsAt,
		&i.RescheduleExpiresAt,
		&i.RescheduleState,
		&i.CancelledByRole,
		&i.RefundMinor,
		&i.RefundSellerShareMinor,
		&i.RefundState,
		&i.RefundSellerLiability,
		&i.NoShowAbsentRole,
		&i.NoShowState,
		&i.NoShowResolvesAt,
		&i.ReviewRating,
		&i.ReviewBody,
		&i.HasReview,
		&i.PayoutState,
		&i.PayoutNetMinor,
		&i.PayoutRecoveryMinor,
		&i.PayoutBankName,
		&i.PayoutAccountLast4,
		&i.IssueResolution,
	)
	return i, err
}

const notificationTarget = `-- name: NotificationTarget :one
SELECT kind, (offer_id IS NOT NULL)::boolean AS is_offer, (payment_exception_id IS NOT NULL)::boolean AS is_payment FROM notification_outbox WHERE id = $1 AND state = 'processing'
`

type NotificationTargetRow struct {
	Kind      string
	IsOffer   bool
	IsPayment bool
}

func (q *Queries) NotificationTarget(ctx context.Context, id string) (NotificationTargetRow, error) {
	row := q.db.QueryRow(ctx, notificationTarget, id)
	var i NotificationTargetRow
	err := row.Scan(&i.Kind, &i.IsOffer, &i.IsPayment)
	return i, err
}

const offerNotificationContext = `-- name: OfferNotificationContext :one
SELECT n.kind, o.id AS offer_id, identity.normalized_identifier AS recipient_email, recipient.timezone AS recipient_timezone,
       (recipient.id = sp.user_id)::boolean AS recipient_is_seller, owner.display_name AS seller_name, sp.handle, sp.timezone AS seller_timezone,
       o.buyer_name, o.duration_minutes, o.state AS offer_state, o.version, o.expires_at, o.checkout_expires_at,
       COALESCE(v.amount_minor, 0)::bigint AS amount_minor, COALESCE(v.actor, '')::text AS amount_actor
FROM notification_outbox n
JOIN offers o ON o.id = n.offer_id
JOIN seller_profiles sp ON sp.id = o.seller_id
JOIN users owner ON owner.id = sp.user_id
JOIN users recipient ON recipient.id = n.recipient_user_id AND recipient.status = 'active'
JOIN user_identities identity ON identity.user_id = recipient.id AND identity.type = 'email'
LEFT JOIN LATERAL (SELECT amount_minor, actor FROM offer_versions WHERE offer_id = o.id ORDER BY version DESC LIMIT 1) v ON true
WHERE n.id = $1 AND n.state = 'processing' AND (recipient.id = sp.user_id OR recipient.id = o.buyer_user_id)
LIMIT 1
`

type OfferNotificationContextRow struct {
	Kind              string
	OfferID           string
	RecipientEmail    string
	RecipientTimezone string
	RecipientIsSeller bool
	SellerName        string
	Handle            string
	SellerTimezone    string
	BuyerName         string
	DurationMinutes   int32
	OfferState        string
	Version           int32
	ExpiresAt         time.Time
	CheckoutExpiresAt *time.Time
	AmountMinor       int64
	AmountActor       string
}

// Buyers who paid without confirming their email still get their booking emails.
func (q *Queries) OfferNotificationContext(ctx context.Context, id string) (OfferNotificationContextRow, error) {
	row := q.db.QueryRow(ctx, offerNotificationContext, id)
	var i OfferNotificationContextRow
	err := row.Scan(
		&i.Kind,
		&i.OfferID,
		&i.RecipientEmail,
		&i.RecipientTimezone,
		&i.RecipientIsSeller,
		&i.SellerName,
		&i.Handle,
		&i.SellerTimezone,
		&i.BuyerName,
		&i.DurationMinutes,
		&i.OfferState,
		&i.Version,
		&i.ExpiresAt,
		&i.CheckoutExpiresAt,
		&i.AmountMinor,
		&i.AmountActor,
	)
	return i, err
}
