// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: observability.sql

package store

import (
	"context"
	"time"
)

const alertSignals = `-- name: AlertSignals :one
SELECT
  (SELECT count(*) FROM provider_events WHERE state = 'failed')::bigint AS provider_events_failed,
  COALESCE((SELECT extract(epoch FROM now() - min(received_at)) FROM provider_events WHERE state IN ('queued', 'retry')), 0)::double precision AS provider_oldest_pending_seconds,
  (SELECT count(*) FROM notification_outbox WHERE state = 'failed' AND created_at > now() - interval '24 hours')::bigint AS notifications_failed_24h,
  COALESCE((SELECT extract(epoch FROM now() - min(due_at)) FROM notification_outbox WHERE state = 'queued' AND due_at <= now()), 0)::double precision AS notifications_oldest_due_seconds,
  (SELECT count(*) FROM payment_exceptions WHERE state <> 'resolved')::bigint AS payment_exceptions_open,
  (SELECT count(*) FROM provider_cases WHERE state <> 'resolved' AND provider_deadline IS NOT NULL AND provider_deadline < now() + interval '72 hours')::bigint AS provider_cases_due_soon,
  (SELECT count(*) FROM bookings WHERE state = 'confirmed' AND meeting_url IS NULL AND starts_at > now() AND starts_at < now() + interval '2 hours')::bigint AS meetings_missing_link_soon
`

type AlertSignalsRow struct {
	ProviderEventsFailed          int64
	ProviderOldestPendingSeconds  float64
	NotificationsFailed24h        int64
	NotificationsOldestDueSeconds float64
	PaymentExceptionsOpen         int64
	ProviderCasesDueSoon          int64
	MeetingsMissingLinkSoon       int64
}

func (q *Queries) AlertSignals(ctx context.Context) (AlertSignalsRow, error) {
	row := q.db.QueryRow(ctx, alertSignals)
	var i AlertSignalsRow
	err := row.Scan(
		&i.ProviderEventsFailed,
		&i.ProviderOldestPendingSeconds,
		&i.NotificationsFailed24h,
		&i.NotificationsOldestDueSeconds,
		&i.PaymentExceptionsOpen,
		&i.ProviderCasesDueSoon,
		&i.MeetingsMissingLinkSoon,
	)
	return i, err
}

const fireAlert = `-- name: FireAlert :exec
INSERT INTO ops_alerts(key, state, severity, summary, value, first_fired_at, last_notified_at, updated_at)
VALUES ($1, 'firing', $2, $3, $4, now(), $5, now())
ON CONFLICT (key) DO UPDATE SET
  state = 'firing',
  severity = EXCLUDED.severity,
  summary = EXCLUDED.summary,
  value = EXCLUDED.value,
  first_fired_at = CASE WHEN ops_alerts.state = 'resolved' THEN now() ELSE ops_alerts.first_fired_at END,
  last_notified_at = COALESCE(EXCLUDED.last_notified_at, ops_alerts.last_notified_at),
  resolved_at = NULL,
  updated_at = now()
`

type FireAlertParams struct {
	Key        string
	Severity   string
	Summary    string
	Value      float64
	NotifiedAt *time.Time
}

func (q *Queries) FireAlert(ctx context.Context, arg FireAlertParams) error {
	_, err := q.db.Exec(ctx, fireAlert,
		arg.Key,
		arg.Severity,
		arg.Summary,
		arg.Value,
		arg.NotifiedAt,
	)
	return err
}

const getAlert = `-- name: GetAlert :one
SELECT key, state, severity, summary, value, first_fired_at, last_notified_at, resolved_at, updated_at
FROM ops_alerts WHERE key = $1
`

func (q *Queries) GetAlert(ctx context.Context, key string) (OpsAlert, error) {
	row := q.db.QueryRow(ctx, getAlert, key)
	var i OpsAlert
	err := row.Scan(
		&i.Key,
		&i.State,
		&i.Severity,
		&i.Summary,
		&i.Value,
		&i.FirstFiredAt,
		&i.LastNotifiedAt,
		&i.ResolvedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAlerts = `-- name: ListAlerts :many
SELECT key, state, severity, summary, value, first_fired_at, last_notified_at, resolved_at, updated_at
FROM ops_alerts
WHERE state = 'firing' OR resolved_at > now() - interval '7 days'
ORDER BY (state = 'firing') DESC, updated_at DESC
LIMIT 100
`

func (q *Queries) ListAlerts(ctx context.Context) ([]OpsAlert, error) {
	rows, err := q.db.Query(ctx, listAlerts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OpsAlert
	for rows.Next() {
		var i OpsAlert
		if err := rows.Scan(
			&i.Key,
			&i.State,
			&i.Severity,
			&i.Summary,
			&i.Value,
			&i.FirstFiredAt,
			&i.LastNotifiedAt,
			&i.ResolvedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const notificationCountsByState = `-- name: NotificationCountsByState :many
SELECT state, count(*)::bigint AS total FROM notification_outbox GROUP BY state ORDER BY state
`

type NotificationCountsByStateRow struct {
	State string
	Total int64
}

func (q *Queries) NotificationCountsByState(ctx context.Context) ([]NotificationCountsByStateRow, error) {
	rows, err := q.db.Query(ctx, notificationCountsByState)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NotificationCountsByStateRow
	for rows.Next() {
		var i NotificationCountsByStateRow
		if err := rows.Scan(&i.State, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const operationalGauges = `-- name: OperationalGauges :one
SELECT
  (SELECT count(*) FROM provider_cases WHERE state <> 'resolved')::bigint AS provider_cases_open,
  (SELECT count(*) FROM slot_reservations WHERE active AND reservation_kind = 'hold' AND expires_at > now())::bigint AS active_holds,
  (SELECT count(*) FROM bookings WHERE state = 'confirmed' AND starts_at > now() AND starts_at < now() + interval '24 hours')::bigint AS bookings_next_24h,
  (SELECT count(*) FROM ops_alerts WHERE state = 'firing')::bigint AS alerts_firing
`

type OperationalGaugesRow struct {
	ProviderCasesOpen int64
	ActiveHolds       int64
	BookingsNext24h   int64
	AlertsFiring      int64
}

func (q *Queries) OperationalGauges(ctx context.Context) (OperationalGaugesRow, error) {
	row := q.db.QueryRow(ctx, operationalGauges)
	var i OperationalGaugesRow
	err := row.Scan(
		&i.ProviderCasesOpen,
		&i.ActiveHolds,
		&i.BookingsNext24h,
		&i.AlertsFiring,
	)
	return i, err
}

const providerEventCountsByState = `-- name: ProviderEventCountsByState :many
SELECT state, count(*)::bigint AS total FROM provider_events GROUP BY state ORDER BY state
`

type ProviderEventCountsByStateRow struct {
	State string
	Total int64
}

func (q *Queries) ProviderEventCountsByState(ctx context.Context) ([]ProviderEventCountsByStateRow, error) {
	rows, err := q.db.Query(ctx, providerEventCountsByState)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProviderEventCountsByStateRow
	for rows.Next() {
		var i ProviderEventCountsByStateRow
		if err := rows.Scan(&i.State, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordWorkerBeat = `-- name: RecordWorkerBeat :exec
INSERT INTO worker_heartbeats(name, instance, last_beat_at)
VALUES ($1, $2, now())
ON CONFLICT (name) DO UPDATE SET instance = EXCLUDED.instance, last_beat_at = now()
`

type RecordWorkerBeatParams struct {
	Name     string
	Instance string
}

func (q *Queries) RecordWorkerBeat(ctx context.Context, arg RecordWorkerBeatParams) error {
	_, err := q.db.Exec(ctx, recordWorkerBeat, arg.Name, arg.Instance)
	return err
}

const recordWorkerError = `-- name: RecordWorkerError :exec
INSERT INTO worker_heartbeats(name, instance, last_beat_at, last_error_at, last_error)
VALUES ($1, $2, now(), now(), $3::text)
ON CONFLICT (name) DO UPDATE SET instance = EXCLUDED.instance, last_beat_at = now(), last_error_at = now(), last_error = EXCLUDED.last_error
`

type RecordWorkerErrorParams struct {
	Name      string
	Instance  string
	ErrorText string
}

func (q *Queries) RecordWorkerError(ctx context.Context, arg RecordWorkerErrorParams) error {
	_, err := q.db.Exec(ctx, recordWorkerError, arg.Name, arg.Instance, arg.ErrorText)
	return err
}

const resolveAlert = `-- name: ResolveAlert :exec
UPDATE ops_alerts SET state = 'resolved', resolved_at = now(), updated_at = now() WHERE key = $1 AND state = 'firing'
`

func (q *Queries) ResolveAlert(ctx context.Context, key string) error {
	_, err := q.db.Exec(ctx, resolveAlert, key)
	return err
}

const workerHeartbeats = `-- name: WorkerHeartbeats :many
SELECT name, instance, last_beat_at, last_error_at, last_error,
       extract(epoch FROM now() - last_beat_at)::double precision AS age_seconds
FROM worker_heartbeats ORDER BY name
`

type WorkerHeartbeatsRow struct {
	Name        string
	Instance    string
	LastBeatAt  time.Time
	LastErrorAt *time.Time
	LastError   *string
	AgeSeconds  float64
}

func (q *Queries) WorkerHeartbeats(ctx context.Context) ([]WorkerHeartbeatsRow, error) {
	rows, err := q.db.Query(ctx, workerHeartbeats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkerHeartbeatsRow
	for rows.Next() {
		var i WorkerHeartbeatsRow
		if err := rows.Scan(
			&i.Name,
			&i.Instance,
			&i.LastBeatAt,
			&i.LastErrorAt,
			&i.LastError,
			&i.AgeSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
