// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payments.sql

package store

import (
	"context"
	"time"
)

const addPaymentException = `-- name: AddPaymentException :exec
INSERT INTO payment_exceptions(id, payment_attempt_id, kind, state, provider_case_reference, amount_minor, currency, reason, evidence)
VALUES (gen_random_uuid(), $1::uuid, $2, 'open', $3::text, $4::bigint, $5::text, $6,
        jsonb_build_object('quote_id', $7::text))
ON CONFLICT (payment_attempt_id, kind) WHERE payment_attempt_id IS NOT NULL DO NOTHING
`

type AddPaymentExceptionParams struct {
	PaymentAttemptID string
	Kind             string
	Reference        string
	AmountMinor      int64
	Currency         string
	Reason           string
	QuoteID          string
}

func (q *Queries) AddPaymentException(ctx context.Context, arg AddPaymentExceptionParams) error {
	_, err := q.db.Exec(ctx, addPaymentException,
		arg.PaymentAttemptID,
		arg.Kind,
		arg.Reference,
		arg.AmountMinor,
		arg.Currency,
		arg.Reason,
		arg.QuoteID,
	)
	return err
}

const bookingIDForQuote = `-- name: BookingIDForQuote :one
SELECT id FROM bookings WHERE quote_id = $1::uuid
`

func (q *Queries) BookingIDForQuote(ctx context.Context, quoteID string) (string, error) {
	row := q.db.QueryRow(ctx, bookingIDForQuote, quoteID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const confirmHoldAsBooking = `-- name: ConfirmHoldAsBooking :exec
UPDATE slot_reservations SET reservation_kind = 'booking', expires_at = NULL, booking_id = $1::uuid
WHERE quote_id = $2::uuid AND active
`

type ConfirmHoldAsBookingParams struct {
	BookingID string
	QuoteID   string
}

func (q *Queries) ConfirmHoldAsBooking(ctx context.Context, arg ConfirmHoldAsBookingParams) error {
	_, err := q.db.Exec(ctx, confirmHoldAsBooking, arg.BookingID, arg.QuoteID)
	return err
}

const convertOffer = `-- name: ConvertOffer :execrows
UPDATE offers SET state = 'converted', converted_booking_id = $1::uuid
WHERE id = $2 AND state IN ('agreed', 'expired')
`

type ConvertOfferParams struct {
	BookingID string
	ID        string
}

func (q *Queries) ConvertOffer(ctx context.Context, arg ConvertOfferParams) (int64, error) {
	result, err := q.db.Exec(ctx, convertOffer, arg.BookingID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const convertQuote = `-- name: ConvertQuote :exec
UPDATE quotes SET state = 'converted' WHERE id = $1
`

func (q *Queries) ConvertQuote(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, convertQuote, id)
	return err
}

const createPaidBookingFromQuote = `-- name: CreatePaidBookingFromQuote :execrows
INSERT INTO bookings(id, quote_id, seller_id, buyer_user_id, buyer_name, guest_email, duration_minutes, starts_at, gross_minor, currency, state, payment_state, quote_snapshot, meeting_deadline)
SELECT $1::uuid, q.id, q.seller_id, q.buyer_user_id, q.buyer_name, $2::text, q.duration_minutes, q.starts_at, q.gross_minor, q.currency, 'confirmed', 'paid',
       jsonb_build_object('quote_id', q.id, 'offer_id', q.offer_id, 'price_minor', q.gross_minor, 'currency', q.currency, 'duration_minutes', q.duration_minutes, 'starts_at', q.starts_at, 'payment_mode', 'kora_escrow'),
       q.starts_at - interval '30 minutes'
FROM quotes q WHERE q.id = $3::uuid
`

type CreatePaidBookingFromQuoteParams struct {
	BookingID  string
	BuyerEmail string
	QuoteID    string
}

func (q *Queries) CreatePaidBookingFromQuote(ctx context.Context, arg CreatePaidBookingFromQuoteParams) (int64, error) {
	result, err := q.db.Exec(ctx, createPaidBookingFromQuote, arg.BookingID, arg.BuyerEmail, arg.QuoteID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createPaymentAllocation = `-- name: CreatePaymentAllocation :exec
INSERT INTO payment_allocations(id, booking_id, gross_minor, deduction_minor, seller_entitlement_minor, processor_cost_minor, settlement_route, settlement_route_snapshot, fee_basis_points)
VALUES (gen_random_uuid(), $1, $2, $3, $4, $5, 'approved_transfer',
        jsonb_build_object('provider', 'kora', 'environment', $6::text, 'reference', $7::text, 'route', 'approved_transfer'),
        $8)
`

type CreatePaymentAllocationParams struct {
	BookingID              string
	GrossMinor             int64
	DeductionMinor         int64
	SellerEntitlementMinor int64
	ProcessorCostMinor     int64
	Environment            string
	Reference              string
	FeeBasisPoints         int32
}

func (q *Queries) CreatePaymentAllocation(ctx context.Context, arg CreatePaymentAllocationParams) error {
	_, err := q.db.Exec(ctx, createPaymentAllocation,
		arg.BookingID,
		arg.GrossMinor,
		arg.DeductionMinor,
		arg.SellerEntitlementMinor,
		arg.ProcessorCostMinor,
		arg.Environment,
		arg.Reference,
		arg.FeeBasisPoints,
	)
	return err
}

const createSettlementItemForBooking = `-- name: CreateSettlementItemForBooking :exec
INSERT INTO settlement_items(id, allocation_id, route, state, provider_reference)
SELECT gen_random_uuid(), id, settlement_route, 'payout_scheduled', $1::text
FROM payment_allocations WHERE booking_id = $2::uuid
`

type CreateSettlementItemForBookingParams struct {
	Reference string
	BookingID string
}

func (q *Queries) CreateSettlementItemForBooking(ctx context.Context, arg CreateSettlementItemForBookingParams) error {
	_, err := q.db.Exec(ctx, createSettlementItemForBooking, arg.Reference, arg.BookingID)
	return err
}

const lockHoldForQuote = `-- name: LockHoldForQuote :one
SELECT active, expires_at FROM slot_reservations WHERE quote_id = $1::uuid FOR UPDATE
`

type LockHoldForQuoteRow struct {
	Active    bool
	ExpiresAt *time.Time
}

func (q *Queries) LockHoldForQuote(ctx context.Context, quoteID string) (LockHoldForQuoteRow, error) {
	row := q.db.QueryRow(ctx, lockHoldForQuote, quoteID)
	var i LockHoldForQuoteRow
	err := row.Scan(&i.Active, &i.ExpiresAt)
	return i, err
}

const lockOfferState = `-- name: LockOfferState :one
SELECT state FROM offers WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockOfferState(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, lockOfferState, id)
	var state string
	err := row.Scan(&state)
	return state, err
}

const lockPaymentAttemptByReference = `-- name: LockPaymentAttemptByReference :one
SELECT id, quote_id, expected_minor, currency, canonical_state, approved_fee_minor, fee_basis_points, provider_transaction_id, booking_id, COALESCE(channel, '')::text AS channel
FROM payment_attempts
WHERE provider = 'kora' AND environment = $1 AND merchant_reference = $2
FOR UPDATE
`

type LockPaymentAttemptByReferenceParams struct {
	Environment string
	Reference   string
}

type LockPaymentAttemptByReferenceRow struct {
	ID                    string
	QuoteID               *string
	ExpectedMinor         int64
	Currency              string
	CanonicalState        string
	ApprovedFeeMinor      *int64
	FeeBasisPoints        *int32
	ProviderTransactionID *string
	BookingID             *string
	Channel               string
}

func (q *Queries) LockPaymentAttemptByReference(ctx context.Context, arg LockPaymentAttemptByReferenceParams) (LockPaymentAttemptByReferenceRow, error) {
	row := q.db.QueryRow(ctx, lockPaymentAttemptByReference, arg.Environment, arg.Reference)
	var i LockPaymentAttemptByReferenceRow
	err := row.Scan(
		&i.ID,
		&i.QuoteID,
		&i.ExpectedMinor,
		&i.Currency,
		&i.CanonicalState,
		&i.ApprovedFeeMinor,
		&i.FeeBasisPoints,
		&i.ProviderTransactionID,
		&i.BookingID,
		&i.Channel,
	)
	return i, err
}

const lockQuoteForPayment = `-- name: LockQuoteForPayment :one
SELECT seller_id, buyer_user_id, buyer_name, duration_minutes, starts_at, expires_at, state, offer_id
FROM quotes WHERE id = $1 FOR UPDATE
`

type LockQuoteForPaymentRow struct {
	SellerID        string
	BuyerUserID     string
	BuyerName       string
	DurationMinutes int32
	StartsAt        time.Time
	ExpiresAt       time.Time
	State           string
	OfferID         *string
}

func (q *Queries) LockQuoteForPayment(ctx context.Context, id string) (LockQuoteForPaymentRow, error) {
	row := q.db.QueryRow(ctx, lockQuoteForPayment, id)
	var i LockQuoteForPaymentRow
	err := row.Scan(
		&i.SellerID,
		&i.BuyerUserID,
		&i.BuyerName,
		&i.DurationMinutes,
		&i.StartsAt,
		&i.ExpiresAt,
		&i.State,
		&i.OfferID,
	)
	return i, err
}

const lockSellerAvailability = `-- name: LockSellerAvailability :one
SELECT (u.status = 'active' AND NOT sp.paused)::boolean AS available
FROM seller_profiles sp JOIN users u ON u.id = sp.user_id
WHERE sp.id = $1
FOR UPDATE OF sp
`

func (q *Queries) LockSellerAvailability(ctx context.Context, sellerID string) (bool, error) {
	row := q.db.QueryRow(ctx, lockSellerAvailability, sellerID)
	var available bool
	err := row.Scan(&available)
	return available, err
}

const markPaymentAttemptException = `-- name: MarkPaymentAttemptException :exec
UPDATE payment_attempts
SET canonical_state = 'exception', provider_transaction_id = COALESCE($1, provider_transaction_id), last_verified_at = now(), updated_at = now()
WHERE id = $2
`

type MarkPaymentAttemptExceptionParams struct {
	TransactionID *string
	ID            string
}

func (q *Queries) MarkPaymentAttemptException(ctx context.Context, arg MarkPaymentAttemptExceptionParams) error {
	_, err := q.db.Exec(ctx, markPaymentAttemptException, arg.TransactionID, arg.ID)
	return err
}

const markPaymentAttemptSuccess = `-- name: MarkPaymentAttemptSuccess :exec
UPDATE payment_attempts
SET booking_id = COALESCE($1::uuid, booking_id), canonical_state = 'success',
    provider_transaction_id = COALESCE($2, provider_transaction_id), last_verified_at = now(), updated_at = now()
WHERE id = $3
`

type MarkPaymentAttemptSuccessParams struct {
	BookingID     *string
	TransactionID *string
	ID            string
}

func (q *Queries) MarkPaymentAttemptSuccess(ctx context.Context, arg MarkPaymentAttemptSuccessParams) error {
	_, err := q.db.Exec(ctx, markPaymentAttemptSuccess, arg.BookingID, arg.TransactionID, arg.ID)
	return err
}

const paymentAttemptOwnedByBuyer = `-- name: PaymentAttemptOwnedByBuyer :one
SELECT EXISTS (
  SELECT 1 FROM payment_attempts p JOIN quotes q ON q.id = p.quote_id
  WHERE q.id = $1 AND q.buyer_user_id = $2
    AND p.provider = 'kora' AND p.environment = $3 AND p.merchant_reference = $4
)::boolean AS owned
`

type PaymentAttemptOwnedByBuyerParams struct {
	QuoteID     string
	BuyerUserID string
	Environment string
	Reference   string
}

func (q *Queries) PaymentAttemptOwnedByBuyer(ctx context.Context, arg PaymentAttemptOwnedByBuyerParams) (bool, error) {
	row := q.db.QueryRow(ctx, paymentAttemptOwnedByBuyer,
		arg.QuoteID,
		arg.BuyerUserID,
		arg.Environment,
		arg.Reference,
	)
	var owned bool
	err := row.Scan(&owned)
	return owned, err
}

const recordPaymentAttemptStatus = `-- name: RecordPaymentAttemptStatus :exec
UPDATE payment_attempts
SET canonical_state = $1, provider_transaction_id = COALESCE($2, provider_transaction_id), last_verified_at = now(), updated_at = now()
WHERE id = $3 AND canonical_state NOT IN ('success', 'exception')
`

type RecordPaymentAttemptStatusParams struct {
	State         string
	TransactionID *string
	ID            string
}

func (q *Queries) RecordPaymentAttemptStatus(ctx context.Context, arg RecordPaymentAttemptStatusParams) error {
	_, err := q.db.Exec(ctx, recordPaymentAttemptStatus, arg.State, arg.TransactionID, arg.ID)
	return err
}

const recordPaymentCard = `-- name: RecordPaymentCard :exec
UPDATE payment_attempts SET card_country = $1::text, card_brand = $2::text, updated_at = now()
WHERE id = $3
`

type RecordPaymentCardParams struct {
	CardCountry *string
	CardBrand   *string
	ID          string
}

func (q *Queries) RecordPaymentCard(ctx context.Context, arg RecordPaymentCardParams) error {
	_, err := q.db.Exec(ctx, recordPaymentCard, arg.CardCountry, arg.CardBrand, arg.ID)
	return err
}

const recordPaymentChannel = `-- name: RecordPaymentChannel :exec
UPDATE payment_attempts SET channel = COALESCE(NULLIF($1::text, ''), channel), paid_minor = $2::bigint, updated_at = now()
WHERE id = $3
`

type RecordPaymentChannelParams struct {
	Channel   string
	PaidMinor int64
	ID        string
}

func (q *Queries) RecordPaymentChannel(ctx context.Context, arg RecordPaymentChannelParams) error {
	_, err := q.db.Exec(ctx, recordPaymentChannel, arg.Channel, arg.PaidMinor, arg.ID)
	return err
}

const recordServerProductEvent = `-- name: RecordServerProductEvent :exec
INSERT INTO product_events(id, event_name, subject_hash, environment, props, occurred_at, seller_id)
VALUES (gen_random_uuid(), $1, $2, $3, '{}', now(), $4)
`

type RecordServerProductEventParams struct {
	EventName   string
	SubjectHash []byte
	Environment string
	SellerID    *string
}

func (q *Queries) RecordServerProductEvent(ctx context.Context, arg RecordServerProductEventParams) error {
	_, err := q.db.Exec(ctx, recordServerProductEvent,
		arg.EventName,
		arg.SubjectHash,
		arg.Environment,
		arg.SellerID,
	)
	return err
}

const verifiedEmailForUser = `-- name: VerifiedEmailForUser :one
SELECT normalized_identifier FROM user_identities
WHERE user_id = $1 AND type = 'email' AND verified_at IS NOT NULL
ORDER BY verified_at DESC LIMIT 1
`

func (q *Queries) VerifiedEmailForUser(ctx context.Context, userID string) (string, error) {
	row := q.db.QueryRow(ctx, verifiedEmailForUser, userID)
	var normalized_identifier string
	err := row.Scan(&normalized_identifier)
	return normalized_identifier, err
}
