// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: provider.sql

package store

import (
	"context"
	"time"
)

const approvedChannelFee = `-- name: ApprovedChannelFee :one
SELECT percent_bps, fixed_minor, cap_minor FROM provider_fee_schedules
WHERE provider = 'kora' AND currency = $1 AND channel = $2 AND approved_at IS NOT NULL AND effective_from <= now()
ORDER BY effective_from DESC LIMIT 1
`

type ApprovedChannelFeeParams struct {
	Currency string
	Channel  string
}

type ApprovedChannelFeeRow struct {
	PercentBps int32
	FixedMinor int64
	CapMinor   *int64
}

func (q *Queries) ApprovedChannelFee(ctx context.Context, arg ApprovedChannelFeeParams) (ApprovedChannelFeeRow, error) {
	row := q.db.QueryRow(ctx, approvedChannelFee, arg.Currency, arg.Channel)
	var i ApprovedChannelFeeRow
	err := row.Scan(&i.PercentBps, &i.FixedMinor, &i.CapMinor)
	return i, err
}

const checkoutQuote = `-- name: CheckoutQuote :one
SELECT q.id, q.seller_id::text AS seller_id, q.buyer_name, q.gross_minor, q.state, q.expires_at, sp.paused, (sp.readiness_state = 'ready')::boolean AS ready,
       EXISTS (SELECT 1 FROM seller_payout_accounts spa WHERE spa.seller_id = sp.id)::boolean AS has_payout_account, i.normalized_identifier AS buyer_email,
       q.currency::text AS currency, sp.country::text AS seller_country
FROM quotes q
JOIN seller_profiles sp ON sp.id = q.seller_id
JOIN user_identities i ON i.user_id = q.buyer_user_id AND i.type = 'email'
WHERE q.id = $1 AND q.buyer_user_id = $2
LIMIT 1
`

type CheckoutQuoteParams struct {
	QuoteID     string
	BuyerUserID string
}

type CheckoutQuoteRow struct {
	ID               string
	SellerID         string
	BuyerName        string
	GrossMinor       int64
	State            string
	ExpiresAt        time.Time
	Paused           bool
	Ready            bool
	HasPayoutAccount bool
	BuyerEmail       string
	Currency         string
	SellerCountry    string
}

func (q *Queries) CheckoutQuote(ctx context.Context, arg CheckoutQuoteParams) (CheckoutQuoteRow, error) {
	row := q.db.QueryRow(ctx, checkoutQuote, arg.QuoteID, arg.BuyerUserID)
	var i CheckoutQuoteRow
	err := row.Scan(
		&i.ID,
		&i.SellerID,
		&i.BuyerName,
		&i.GrossMinor,
		&i.State,
		&i.ExpiresAt,
		&i.Paused,
		&i.Ready,
		&i.HasPayoutAccount,
		&i.BuyerEmail,
		&i.Currency,
		&i.SellerCountry,
	)
	return i, err
}

const claimNextProviderEvent = `-- name: ClaimNextProviderEvent :one
SELECT id, provider_reference FROM provider_events
WHERE provider = 'kora' AND environment = $1
  AND ((state IN ('queued', 'retry') AND next_attempt_at <= now()) OR (state = 'processing' AND claimed_at < now() - interval '2 minutes'))
ORDER BY received_at
FOR UPDATE SKIP LOCKED
LIMIT 1
`

type ClaimNextProviderEventRow struct {
	ID                string
	ProviderReference *string
}

func (q *Queries) ClaimNextProviderEvent(ctx context.Context, environment string) (ClaimNextProviderEventRow, error) {
	row := q.db.QueryRow(ctx, claimNextProviderEvent, environment)
	var i ClaimNextProviderEventRow
	err := row.Scan(&i.ID, &i.ProviderReference)
	return i, err
}

const claimPaymentInitialization = `-- name: ClaimPaymentInitialization :execrows
UPDATE payment_attempts SET canonical_state = 'initialization_started', updated_at = now()
WHERE id = $1 AND canonical_state = 'initializing' AND authorization_url IS NULL
`

func (q *Queries) ClaimPaymentInitialization(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, claimPaymentInitialization, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const failProviderEvent = `-- name: FailProviderEvent :exec
UPDATE provider_events
SET state = CASE WHEN $1::boolean AND processing_attempts < 8 THEN 'retry' ELSE 'failed' END,
    last_error_code = $2::text,
    claimed_at = NULL,
    next_attempt_at = now() + LEAST(interval '15 minutes', interval '5 seconds' * power(2, LEAST(processing_attempts, 8)))
WHERE id = $3
`

type FailProviderEventParams struct {
	Retry     bool
	ErrorCode string
	ID        string
}

func (q *Queries) FailProviderEvent(ctx context.Context, arg FailProviderEventParams) error {
	_, err := q.db.Exec(ctx, failProviderEvent, arg.Retry, arg.ErrorCode, arg.ID)
	return err
}

const insertProviderEvent = `-- name: InsertProviderEvent :exec
INSERT INTO provider_events(id, provider, environment, event_digest, raw_body_hash, state, event_type, provider_reference, minimal_payload)
VALUES (gen_random_uuid(), 'kora', $1, $2, $2, $3, $4::text, NULLIF($5::text, ''), $6::jsonb)
ON CONFLICT (provider, environment, event_digest) DO NOTHING
`

type InsertProviderEventParams struct {
	Environment string
	Digest      []byte
	State       string
	EventType   string
	Reference   string
	Payload     []byte
}

func (q *Queries) InsertProviderEvent(ctx context.Context, arg InsertProviderEventParams) error {
	_, err := q.db.Exec(ctx, insertProviderEvent,
		arg.Environment,
		arg.Digest,
		arg.State,
		arg.EventType,
		arg.Reference,
		arg.Payload,
	)
	return err
}

const markInitializationUnknown = `-- name: MarkInitializationUnknown :exec
UPDATE payment_attempts SET canonical_state = 'initialization_unknown', updated_at = now()
WHERE id = $1 AND canonical_state = 'initialization_started'
`

func (q *Queries) MarkInitializationUnknown(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, markInitializationUnknown, id)
	return err
}

const markProviderEventProcessed = `-- name: MarkProviderEventProcessed :exec
UPDATE provider_events SET state = 'processed', last_error_code = NULL, claimed_at = NULL WHERE id = $1
`

func (q *Queries) MarkProviderEventProcessed(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, markProviderEventProcessed, id)
	return err
}

const markProviderEventProcessing = `-- name: MarkProviderEventProcessing :exec
UPDATE provider_events SET state = 'processing', processing_attempts = processing_attempts + 1, claimed_at = now() WHERE id = $1
`

func (q *Queries) MarkProviderEventProcessing(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, markProviderEventProcessing, id)
	return err
}

const savePaymentAuthorization = `-- name: SavePaymentAuthorization :execrows
UPDATE payment_attempts SET authorization_url = $1::text, access_code = $2::text, canonical_state = 'awaiting_payment', updated_at = now()
WHERE id = $3 AND canonical_state = 'initialization_started'
`

type SavePaymentAuthorizationParams struct {
	AuthorizationUrl string
	AccessCode       string
	ID               string
}

func (q *Queries) SavePaymentAuthorization(ctx context.Context, arg SavePaymentAuthorizationParams) (int64, error) {
	result, err := q.db.Exec(ctx, savePaymentAuthorization, arg.AuthorizationUrl, arg.AccessCode, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const saveTransferInstructions = `-- name: SaveTransferInstructions :execrows
UPDATE payment_attempts SET transfer_details = $1::jsonb, instructions_expire_at = $2::timestamptz, canonical_state = 'awaiting_payment', updated_at = now()
WHERE id = $3 AND canonical_state = 'initialization_started'
`

type SaveTransferInstructionsParams struct {
	Details   []byte
	ExpiresAt time.Time
	ID        string
}

func (q *Queries) SaveTransferInstructions(ctx context.Context, arg SaveTransferInstructionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, saveTransferInstructions, arg.Details, arg.ExpiresAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertPaymentAttempt = `-- name: UpsertPaymentAttempt :one
INSERT INTO payment_attempts(id, quote_id, provider, environment, merchant_reference, expected_minor, currency, canonical_state, approved_fee_minor, fee_basis_points, channel, buyer_fee_minor)
VALUES (gen_random_uuid(), $1::uuid, 'kora', $2, $3, $4, $5::text, 'initializing', $6::bigint, $7::int, $8::text, $9::bigint)
ON CONFLICT (provider, environment, merchant_reference) DO UPDATE SET updated_at = now()
RETURNING id, canonical_state, COALESCE(authorization_url, '')::text AS authorization_url, transfer_details, instructions_expire_at,
  COALESCE(approved_fee_minor, 0)::bigint AS approved_fee_minor
`

type UpsertPaymentAttemptParams struct {
	QuoteID          string
	Environment      string
	Reference        string
	ExpectedMinor    int64
	Currency         string
	ApprovedFeeMinor int64
	FeeBasisPoints   int32
	Channel          string
	BuyerFeeMinor    int64
}

type UpsertPaymentAttemptRow struct {
	ID                   string
	CanonicalState       string
	AuthorizationUrl     string
	TransferDetails      []byte
	InstructionsExpireAt *time.Time
	ApprovedFeeMinor     int64
}

func (q *Queries) UpsertPaymentAttempt(ctx context.Context, arg UpsertPaymentAttemptParams) (UpsertPaymentAttemptRow, error) {
	row := q.db.QueryRow(ctx, upsertPaymentAttempt,
		arg.QuoteID,
		arg.Environment,
		arg.Reference,
		arg.ExpectedMinor,
		arg.Currency,
		arg.ApprovedFeeMinor,
		arg.FeeBasisPoints,
		arg.Channel,
		arg.BuyerFeeMinor,
	)
	var i UpsertPaymentAttemptRow
	err := row.Scan(
		&i.ID,
		&i.CanonicalState,
		&i.AuthorizationUrl,
		&i.TransferDetails,
		&i.InstructionsExpireAt,
		&i.ApprovedFeeMinor,
	)
	return i, err
}

const upsertProviderCase = `-- name: UpsertProviderCase :exec
INSERT INTO provider_cases(provider, environment, provider_case_id, payment_attempt_id, provider_reference, case_type, state, amount_minor, currency, provider_deadline, last_event_type)
VALUES ('kora', $1, $2,
        (SELECT pa.id FROM payment_attempts pa WHERE pa.provider = 'kora' AND pa.environment = $1 AND pa.merchant_reference = $3 LIMIT 1),
        $3, $4, $5, NULLIF($6::bigint, 0), NULLIF($7::text, ''), $8::timestamptz, $9)
ON CONFLICT (provider, environment, provider_case_id) DO UPDATE SET
  state = EXCLUDED.state,
  amount_minor = COALESCE(EXCLUDED.amount_minor, provider_cases.amount_minor),
  currency = COALESCE(EXCLUDED.currency, provider_cases.currency),
  provider_deadline = COALESCE(EXCLUDED.provider_deadline, provider_cases.provider_deadline),
  last_event_type = EXCLUDED.last_event_type,
  updated_at = now()
`

type UpsertProviderCaseParams struct {
	Environment string
	CaseID      string
	Reference   string
	CaseType    string
	State       string
	AmountMinor int64
	Currency    string
	Deadline    *time.Time
	EventType   string
}

func (q *Queries) UpsertProviderCase(ctx context.Context, arg UpsertProviderCaseParams) error {
	_, err := q.db.Exec(ctx, upsertProviderCase,
		arg.Environment,
		arg.CaseID,
		arg.Reference,
		arg.CaseType,
		arg.State,
		arg.AmountMinor,
		arg.Currency,
		arg.Deadline,
		arg.EventType,
	)
	return err
}
