// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: refunds.sql

package store

import (
	"context"
	"time"
)

const applyRecovery = `-- name: ApplyRecovery :exec
UPDATE seller_recoveries SET recovered_minor = recovered_minor + $1, updated_at = now() WHERE id = $2::uuid
`

type ApplyRecoveryParams struct {
	AmountMinor int64
	ID          string
}

func (q *Queries) ApplyRecovery(ctx context.Context, arg ApplyRecoveryParams) error {
	_, err := q.db.Exec(ctx, applyRecovery, arg.AmountMinor, arg.ID)
	return err
}

const cancelUpcomingBookingMail = `-- name: CancelUpcomingBookingMail :exec
UPDATE notification_outbox SET state = 'cancelled', claimed_at = NULL, last_error_code = $1::text
WHERE booking_id = $2::uuid AND state = 'queued'
  AND (kind LIKE 'booking_reminder_%' OR kind LIKE 'meeting_link_due_%' OR kind = 'review_request_buyer' OR kind = 'meeting_link_ready_buyer')
`

type CancelUpcomingBookingMailParams struct {
	ReasonCode string
	BookingID  string
}

func (q *Queries) CancelUpcomingBookingMail(ctx context.Context, arg CancelUpcomingBookingMailParams) error {
	_, err := q.db.Exec(ctx, cancelUpcomingBookingMail, arg.ReasonCode, arg.BookingID)
	return err
}

const claimDueRefunds = `-- name: ClaimDueRefunds :many
WITH due AS (
  SELECT id FROM refunds
  WHERE state IN ('queued', 'submitted') AND next_attempt_at <= now()
  ORDER BY next_attempt_at, id
  FOR UPDATE SKIP LOCKED
  LIMIT $1::int
)
UPDATE refunds r SET next_attempt_at = now() + interval '5 minutes', attempts = r.attempts + 1, updated_at = now()
FROM due WHERE r.id = due.id
RETURNING r.id::text AS id, r.state, r.attempts, r.amount_minor, r.currency, COALESCE(r.provider_refund_id, '')::text AS provider_refund_id,
  COALESCE((SELECT merchant_reference FROM payment_attempts pa WHERE pa.id = r.payment_attempt_id), '')::text AS reference,
  COALESCE((SELECT COALESCE(provider_transaction_id, merchant_reference) FROM payment_attempts pa WHERE pa.id = r.payment_attempt_id), '')::text AS transaction_key
`

type ClaimDueRefundsRow struct {
	ID               string
	State            string
	Attempts         int16
	AmountMinor      int64
	Currency         string
	ProviderRefundID string
	Reference        string
	TransactionKey   string
}

func (q *Queries) ClaimDueRefunds(ctx context.Context, batchSize int32) ([]ClaimDueRefundsRow, error) {
	rows, err := q.db.Query(ctx, claimDueRefunds, batchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimDueRefundsRow
	for rows.Next() {
		var i ClaimDueRefundsRow
		if err := rows.Scan(
			&i.ID,
			&i.State,
			&i.Attempts,
			&i.AmountMinor,
			&i.Currency,
			&i.ProviderRefundID,
			&i.Reference,
			&i.TransactionKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const closeBookingRequests = `-- name: CloseBookingRequests :exec
WITH closed_cancellations AS (
  UPDATE booking_cancellation_requests SET state = 'resolved', resolution = $2::text, resolved_at = now()
  WHERE booking_id = $1::uuid AND state = 'open'
)
UPDATE reschedule_requests SET state = 'expired', version = version + 1
WHERE booking_id = $1::uuid AND state = 'pending'
`

type CloseBookingRequestsParams struct {
	BookingID  string
	Resolution string
}

func (q *Queries) CloseBookingRequests(ctx context.Context, arg CloseBookingRequestsParams) error {
	_, err := q.db.Exec(ctx, closeBookingRequests, arg.BookingID, arg.Resolution)
	return err
}

const createRefund = `-- name: CreateRefund :one
INSERT INTO refunds(booking_id, payment_attempt_id, amount_minor, currency, platform_share_minor, seller_share_minor, reason, state, requested_by, note, seller_liability)
VALUES ($1::uuid, $2::uuid, $3, $4, $5, $6,
        $7, $8, $9::uuid, $10::text, $11::text)
RETURNING id::text
`

type CreateRefundParams struct {
	BookingID          string
	PaymentAttemptID   *string
	AmountMinor        int64
	Currency           string
	PlatformShareMinor int64
	SellerShareMinor   int64
	Reason             string
	State              string
	RequestedBy        *string
	Note               *string
	SellerLiability    string
}

func (q *Queries) CreateRefund(ctx context.Context, arg CreateRefundParams) (string, error) {
	row := q.db.QueryRow(ctx, createRefund,
		arg.BookingID,
		arg.PaymentAttemptID,
		arg.AmountMinor,
		arg.Currency,
		arg.PlatformShareMinor,
		arg.SellerShareMinor,
		arg.Reason,
		arg.State,
		arg.RequestedBy,
		arg.Note,
		arg.SellerLiability,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const insertSellerRecovery = `-- name: InsertSellerRecovery :exec
INSERT INTO seller_recoveries(seller_id, refund_id, amount_minor, currency)
VALUES ($1::uuid, $2::uuid, $3, $4)
ON CONFLICT (refund_id) DO NOTHING
`

type InsertSellerRecoveryParams struct {
	SellerID    string
	RefundID    string
	AmountMinor int64
	Currency    string
}

func (q *Queries) InsertSellerRecovery(ctx context.Context, arg InsertSellerRecoveryParams) error {
	_, err := q.db.Exec(ctx, insertSellerRecovery,
		arg.SellerID,
		arg.RefundID,
		arg.AmountMinor,
		arg.Currency,
	)
	return err
}

const lockBookingForCancellation = `-- name: LockBookingForCancellation :one
SELECT b.id::text AS booking_id, b.state, b.payment_state, b.starts_at, b.created_at, b.duration_minutes, b.gross_minor, b.currency,
       b.buyer_user_id::text AS buyer_user_id, sp.user_id::text AS seller_user_id, sp.id::text AS seller_id, b.cancellation_policy,
       COALESCE(pa.deduction_minor, 0)::bigint AS deduction_minor,
       COALESCE(att.id::text, '')::text AS payment_attempt_id
FROM bookings b
JOIN seller_profiles sp ON sp.id = b.seller_id
LEFT JOIN payment_allocations pa ON pa.booking_id = b.id
LEFT JOIN payment_attempts att ON att.booking_id = b.id AND att.canonical_state = 'success'
WHERE b.id = $1::uuid
FOR UPDATE OF b
`

type LockBookingForCancellationRow struct {
	BookingID          string
	State              string
	PaymentState       string
	StartsAt           time.Time
	CreatedAt          time.Time
	DurationMinutes    int32
	GrossMinor         int64
	Currency           string
	BuyerUserID        string
	SellerUserID       string
	SellerID           string
	CancellationPolicy string
	DeductionMinor     int64
	PaymentAttemptID   string
}

func (q *Queries) LockBookingForCancellation(ctx context.Context, bookingID string) (LockBookingForCancellationRow, error) {
	row := q.db.QueryRow(ctx, lockBookingForCancellation, bookingID)
	var i LockBookingForCancellationRow
	err := row.Scan(
		&i.BookingID,
		&i.State,
		&i.PaymentState,
		&i.StartsAt,
		&i.CreatedAt,
		&i.DurationMinutes,
		&i.GrossMinor,
		&i.Currency,
		&i.BuyerUserID,
		&i.SellerUserID,
		&i.SellerID,
		&i.CancellationPolicy,
		&i.DeductionMinor,
		&i.PaymentAttemptID,
	)
	return i, err
}

const lockOpenRecoveries = `-- name: LockOpenRecoveries :many
SELECT id::text, amount_minor - recovered_minor AS outstanding
FROM seller_recoveries WHERE seller_id = $1::uuid AND recovered_minor < amount_minor
ORDER BY created_at, id
FOR UPDATE
`

type LockOpenRecoveriesRow struct {
	ID          string
	Outstanding int32
}

func (q *Queries) LockOpenRecoveries(ctx context.Context, sellerID string) ([]LockOpenRecoveriesRow, error) {
	rows, err := q.db.Query(ctx, lockOpenRecoveries, sellerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LockOpenRecoveriesRow
	for rows.Next() {
		var i LockOpenRecoveriesRow
		if err := rows.Scan(&i.ID, &i.Outstanding); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockRefundForFinalize = `-- name: LockRefundForFinalize :one
SELECT r.id::text AS id, r.state, r.seller_liability, r.amount_minor, r.currency, r.platform_share_minor, r.seller_share_minor, r.booking_id::text AS booking_id,
       b.seller_id::text AS seller_id, b.gross_minor, b.payment_state, b.buyer_user_id::text AS buyer_user_id
FROM refunds r JOIN bookings b ON b.id = r.booking_id
WHERE r.id = $1::uuid
FOR UPDATE OF r
`

type LockRefundForFinalizeRow struct {
	ID                 string
	State              string
	SellerLiability    string
	AmountMinor        int64
	Currency           string
	PlatformShareMinor int64
	SellerShareMinor   int64
	BookingID          string
	SellerID           string
	GrossMinor         int64
	PaymentState       string
	BuyerUserID        string
}

func (q *Queries) LockRefundForFinalize(ctx context.Context, id string) (LockRefundForFinalizeRow, error) {
	row := q.db.QueryRow(ctx, lockRefundForFinalize, id)
	var i LockRefundForFinalizeRow
	err := row.Scan(
		&i.ID,
		&i.State,
		&i.SellerLiability,
		&i.AmountMinor,
		&i.Currency,
		&i.PlatformShareMinor,
		&i.SellerShareMinor,
		&i.BookingID,
		&i.SellerID,
		&i.GrossMinor,
		&i.PaymentState,
		&i.BuyerUserID,
	)
	return i, err
}

const markBookingCancelled = `-- name: MarkBookingCancelled :exec
UPDATE bookings SET state = 'cancelled', cancelled_at = now(), cancelled_by_role = $1::text, cancellation_reason = $2::text
WHERE id = $3::uuid AND state = 'confirmed'
`

type MarkBookingCancelledParams struct {
	Role      string
	Reason    *string
	BookingID string
}

func (q *Queries) MarkBookingCancelled(ctx context.Context, arg MarkBookingCancelledParams) error {
	_, err := q.db.Exec(ctx, markBookingCancelled, arg.Role, arg.Reason, arg.BookingID)
	return err
}

const markRefundFailed = `-- name: MarkRefundFailed :exec
UPDATE refunds SET state = 'failed', last_error = $1::text, updated_at = now()
WHERE id = $2::uuid AND state IN ('queued', 'submitted', 'pending_approval')
`

type MarkRefundFailedParams struct {
	LastError string
	ID        string
}

func (q *Queries) MarkRefundFailed(ctx context.Context, arg MarkRefundFailedParams) error {
	_, err := q.db.Exec(ctx, markRefundFailed, arg.LastError, arg.ID)
	return err
}

const markRefundProcessed = `-- name: MarkRefundProcessed :exec
UPDATE refunds SET state = 'processed', processed_at = now(), note = COALESCE($1::text, note), approved_by = COALESCE($2::uuid, approved_by), updated_at = now()
WHERE id = $3::uuid
`

type MarkRefundProcessedParams struct {
	Note       *string
	ApprovedBy *string
	ID         string
}

func (q *Queries) MarkRefundProcessed(ctx context.Context, arg MarkRefundProcessedParams) error {
	_, err := q.db.Exec(ctx, markRefundProcessed, arg.Note, arg.ApprovedBy, arg.ID)
	return err
}

const markRefundSubmitted = `-- name: MarkRefundSubmitted :exec
UPDATE refunds SET state = 'submitted', provider_refund_id = $1::text, submitted_at = COALESCE(submitted_at, now()),
  next_attempt_at = now() + make_interval(secs => $2::int), last_error = $3::text, updated_at = now()
WHERE id = $4::uuid AND state IN ('queued', 'submitted')
`

type MarkRefundSubmittedParams struct {
	ProviderRefundID string
	PollSeconds      int32
	LastError        *string
	ID               string
}

func (q *Queries) MarkRefundSubmitted(ctx context.Context, arg MarkRefundSubmittedParams) error {
	_, err := q.db.Exec(ctx, markRefundSubmitted,
		arg.ProviderRefundID,
		arg.PollSeconds,
		arg.LastError,
		arg.ID,
	)
	return err
}

const nudgeRefundByProviderID = `-- name: NudgeRefundByProviderID :exec
UPDATE refunds SET next_attempt_at = now(), updated_at = now() WHERE provider_refund_id = $1::text AND state = 'submitted'
`

func (q *Queries) NudgeRefundByProviderID(ctx context.Context, providerRefundID string) error {
	_, err := q.db.Exec(ctx, nudgeRefundByProviderID, providerRefundID)
	return err
}

const releaseBookingSlot = `-- name: ReleaseBookingSlot :exec
UPDATE slot_reservations SET active = false WHERE booking_id = $1::uuid AND active
`

func (q *Queries) ReleaseBookingSlot(ctx context.Context, bookingID string) error {
	_, err := q.db.Exec(ctx, releaseBookingSlot, bookingID)
	return err
}

const retryRefundLater = `-- name: RetryRefundLater :exec
UPDATE refunds SET next_attempt_at = now() + make_interval(secs => $1::int), last_error = $2::text, updated_at = now()
WHERE id = $3::uuid AND state IN ('queued', 'submitted')
`

type RetryRefundLaterParams struct {
	RetrySeconds int32
	LastError    string
	ID           string
}

func (q *Queries) RetryRefundLater(ctx context.Context, arg RetryRefundLaterParams) error {
	_, err := q.db.Exec(ctx, retryRefundLater, arg.RetrySeconds, arg.LastError, arg.ID)
	return err
}

const sellerRecoverySummary = `-- name: SellerRecoverySummary :one
SELECT COALESCE(sum(amount_minor), 0)::bigint AS total_minor, COALESCE(sum(recovered_minor), 0)::bigint AS recovered_minor
FROM seller_recoveries sr JOIN seller_profiles sp ON sp.id = sr.seller_id
WHERE sp.user_id = $1::uuid
`

type SellerRecoverySummaryRow struct {
	TotalMinor     int64
	RecoveredMinor int64
}

func (q *Queries) SellerRecoverySummary(ctx context.Context, userID string) (SellerRecoverySummaryRow, error) {
	row := q.db.QueryRow(ctx, sellerRecoverySummary, userID)
	var i SellerRecoverySummaryRow
	err := row.Scan(&i.TotalMinor, &i.RecoveredMinor)
	return i, err
}

const setBookingPaymentState = `-- name: SetBookingPaymentState :exec
UPDATE bookings SET payment_state = $1::text WHERE id = $2::uuid
`

type SetBookingPaymentStateParams struct {
	PaymentState string
	BookingID    string
}

func (q *Queries) SetBookingPaymentState(ctx context.Context, arg SetBookingPaymentStateParams) error {
	_, err := q.db.Exec(ctx, setBookingPaymentState, arg.PaymentState, arg.BookingID)
	return err
}
