// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: settlements.sql

package store

import (
	"context"
	"time"
)

const auditSettlementImport = `-- name: AuditSettlementImport :exec
INSERT INTO audit_events(id, actor_id, action, reason, safe_summary)
VALUES (gen_random_uuid(), $1::uuid, 'settlement.imported', 'Imported operator-supplied normalized CSV for provisional review',
        jsonb_build_object('import_id', $2::text, 'matched', $3::int, 'unmatched', $4::int,
                           'amount_mismatch', $5::int, 'currency_mismatch', $6::int, 'duplicates', $7::int))
`

type AuditSettlementImportParams struct {
	ActorID          string
	ImportID         string
	Matched          int32
	Unmatched        int32
	AmountMismatch   int32
	CurrencyMismatch int32
	Duplicates       int32
}

func (q *Queries) AuditSettlementImport(ctx context.Context, arg AuditSettlementImportParams) error {
	_, err := q.db.Exec(ctx, auditSettlementImport,
		arg.ActorID,
		arg.ImportID,
		arg.Matched,
		arg.Unmatched,
		arg.AmountMismatch,
		arg.CurrencyMismatch,
		arg.Duplicates,
	)
	return err
}

const insertSettlementImportRow = `-- name: InsertSettlementImportRow :exec
INSERT INTO settlement_import_rows(import_id, provider, environment, provider_reference, settlement_reference, amount_minor, currency, settled_at, reconciliation_state, settlement_item_id)
VALUES ($1, 'kora', $2, $3, NULLIF($4::text, ''), $5, $6, $7, $8, $9)
`

type InsertSettlementImportRowParams struct {
	ImportID            string
	Environment         string
	Reference           string
	SettlementReference string
	AmountMinor         int64
	Currency            string
	SettledAt           time.Time
	State               string
	SettlementItemID    *string
}

func (q *Queries) InsertSettlementImportRow(ctx context.Context, arg InsertSettlementImportRowParams) error {
	_, err := q.db.Exec(ctx, insertSettlementImportRow,
		arg.ImportID,
		arg.Environment,
		arg.Reference,
		arg.SettlementReference,
		arg.AmountMinor,
		arg.Currency,
		arg.SettledAt,
		arg.State,
		arg.SettlementItemID,
	)
	return err
}

const lockSettlementItem = `-- name: LockSettlementItem :exec
SELECT id FROM settlement_items WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockSettlementItem(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, lockSettlementItem, id)
	return err
}

const settlementItemAlreadyMatched = `-- name: SettlementItemAlreadyMatched :one
SELECT (EXISTS (SELECT 1 FROM settlement_confirmations sc WHERE sc.settlement_item_id = $1 AND sc.reconciliation_state = 'matched')
     OR EXISTS (SELECT 1 FROM settlement_import_rows r WHERE r.settlement_item_id = $1 AND r.reconciliation_state = 'matched'))::boolean AS matched
`

func (q *Queries) SettlementItemAlreadyMatched(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRow(ctx, settlementItemAlreadyMatched, id)
	var matched bool
	err := row.Scan(&matched)
	return matched, err
}

const settlementMatchForReference = `-- name: SettlementMatchForReference :one
SELECT si.id AS settlement_item_id, pa.seller_entitlement_minor, b.currency
FROM payment_attempts p
JOIN payment_allocations pa ON pa.booking_id = p.booking_id
JOIN settlement_items si ON si.allocation_id = pa.id
JOIN bookings b ON b.id = pa.booking_id
WHERE p.provider = 'kora' AND p.environment = $1 AND p.merchant_reference = $2
LIMIT 1
`

type SettlementMatchForReferenceParams struct {
	Environment string
	Reference   string
}

type SettlementMatchForReferenceRow struct {
	SettlementItemID       string
	SellerEntitlementMinor int64
	Currency               string
}

func (q *Queries) SettlementMatchForReference(ctx context.Context, arg SettlementMatchForReferenceParams) (SettlementMatchForReferenceRow, error) {
	row := q.db.QueryRow(ctx, settlementMatchForReference, arg.Environment, arg.Reference)
	var i SettlementMatchForReferenceRow
	err := row.Scan(&i.SettlementItemID, &i.SellerEntitlementMinor, &i.Currency)
	return i, err
}
