<script lang="ts">
	import { onMount } from 'svelte'; import { api } from '$lib/api'; import { formatNaira } from '$lib/money'; import CursorPager from '$lib/components/CursorPager.svelte';
	type Case={id:string;type:string;state:string;provider_case_id:string;provider_reference:string;payment_attempt_id:string|null;amount_minor:number|null;currency:string|null;provider_deadline:string|null;last_event_type:string;updated_at:string};
	let cases=$state<Case[]>([]);let message=$state('');let loading=$state(true);let nextCursor=$state('');
	async function load(cursor=''){loading=true;try{const query=cursor?`?cursor=${encodeURIComponent(cursor)}`:'';const result=await api<{cases:Case[];notice:string;next_cursor:string}>(`/api/v1/ops/provider-cases${query}`);cases=cursor?[...cases,...result.cases]:result.cases;nextCursor=result.next_cursor;message=result.notice}catch(e){message=e instanceof Error?e.message:'Provider cases could not be loaded.'}finally{loading=false}};
	onMount(()=>{void load()});
</script>
<svelte:head><title>Provider cases — Ops · WantMyTime</title></svelte:head>
	<section class="form-page app-page"><a class="back-link" href="/ops/system">← System health</a><p class="eyebrow">Provider case review</p><h1 class="page-heading">Disputes and refunds.</h1><p class="page-intro">Verified provider notifications are matched to payment attempts when possible. This screen records deadlines and status for human review; it does not submit financial actions.</p>{#if message}<p class="notice notice-warning" aria-live="polite">{message}</p>{/if}{#if loading&&!cases.length}<p>Loading provider cases…</p>{:else if cases.length}<div class="list-stack">{#each cases as item}<article class="list-card"><div><strong>{item.type} · {item.state}</strong><p>{item.provider_reference} · provider case {item.provider_case_id}</p><small>{item.last_event_type} · updated {new Date(item.updated_at).toLocaleString()}{item.provider_deadline?` · due ${new Date(item.provider_deadline).toLocaleString()}`:''}</small>{#if item.amount_minor!==null}<p>{item.currency==='NGN'?formatNaira(item.amount_minor):`${item.currency||''} ${item.amount_minor} minor units`}</p>{/if}{#if !item.payment_attempt_id}<p class="notice notice-warning">No matching payment attempt. Manual provider reconciliation is required.</p>{/if}</div></article>{/each}</div><CursorPager cursor={nextCursor} busy={loading} onNext={()=>load(nextCursor)}/>{:else}<p class="page-intro">No open provider cases have been received.</p>{/if}</section>
